### ISSUE TITLE
challenge strength calculation (dragonglass dagger)

### ISSUE THREAD

**Issue by jbrz** [cryogen/throneteki#1026]
I know a recent update changed game text to read the "correct" strength when characters are declared for a challenge, but I was just playing a game against Balon (lord of crossing) declared as an attacker, when I declared as a defender, dragonglass pushes my character above his strength, and should thus be able to oppose, but the game text reads "x does not defend the challenge."  Purely cosmetic, of course, but seems like maybe still an area or two where the recalculations are happening after the declaration.

I haven't looked at the aforementioned previous update(s), so I'll do that this weekend unless one of you responds faster, just wanted to note the issue here.

**Comment by zacchiro** [comment]
Can you clarify if you were indeed unable to defend, or whether you were able to, but the message in the game log was wrong?

**Comment by zacchiro** [comment]
Closing this due to lack of feedback and no evidence of others experience the same issue.
Please reopen if this is still a problem!
