### ISSUE TITLE
Knighted Arianne doesn't get renown from A Tourney For The King

### ISSUE THREAD

**Issue by zacchiro** [cryogen/throneteki#1027]
Just seen in a game i was spectating:

- Arianne Martel has Knighted as attachment
- plot is A Tourney For The King
- Arianne attacks and wins in a power challenge
- but didn't get power from renown

I see no obvious bugs in the implementation of either Knighted or A Tourny For The King, so — if reproducible — it might be a weird (timing?) interaction among adding the trait and looking it up from a plot?

**Comment by ystros** [comment]
Seems to be a problem with gaining / losing traits and recalculating effects accordingly. Your listed scenario:

```
Play character
Attach Knighted
Reveal A Tourney For The King
Win challenge with character
```

did properly grant renown when I tested it. However, this scenario:

```
Play character
Reveal A Tourney For The King
Attach Knighted
Win challenge with character
```

did not, because the effects of Tourney weren't recalculated when the character's trait changed.
