### ISSUE TITLE
Underground Vault

### ISSUE THREAD

**Issue by mjsupina** [cryogen/throneteki#1035]
Underground Vault always gives 2 gold when knelt, instead of giving 1 gold normally and 2 gold only if the gold value on an opponent's revealed plot card is 5 or higher.

**Comment by ystros** [comment]
Thanks for the report! I just tested it and Underground Vault is working properly. Keep in mind that it's a *total gold value* of the plot being 5 or higher, not the printed gold value. So if the you reveal a 4 gold plot but also have a Roseroad out, that's a total gold value of 5, so the opponent would get 2 gold.

http://thronesdb.com/card/06046
