### ISSUE TITLE
"stolen" plaza stand old owner characters

### ISSUE THREAD

**Issue by oldachab** [cryogen/throneteki#1073]
When you take a location with Dagmer or Euron you can't trigger it properly

**Comment by zacchiro** [comment]
I tried this with Euron, and it worked fine for me: I could stand any kneeled character (with the right cost) using Plaza as a Greyjoy player. So I think the situation that induced the bug is more complicated than it seems. Do you have a sequence of actions that cause the bug to appear?

**Comment by zacchiro** [comment]
closing old unreproducible bug report, please reopen if you encounter this again in the wild!
