### ISSUE TITLE
keeping second risen in hand kills character

### ISSUE THREAD

**Issue by oldachab** [cryogen/throneteki#1074]
When you have 2 risen in your hand and use one on a character, not using the second makes your character die

**Comment by DukeTax** [comment]
Can you elaborate on the circumstances in which this happened? I've been doing some (unrelated) testing involving a lot of kill and multiple Risens, and never had this happen.

**Comment by oldachab** [comment]
I had a unique GJ character (i think esgred) and was suffering a military claim. I chose her for claim, had 2 risen in hand, chose to use one risen on her to save her, chose her, and then pass, and she died.
But in similar cases with iron mine + risen today i had not this problem. I have not been in a position with double risen since.

**Comment by DukeTax** [comment]
I just tried but haven't been able to reproduce this. If it does happen again let us know. :)

**Comment by cryogen** [comment]
Closing this as not reproducible, please reopen with more info if it happens again
