### ISSUE TITLE
can't save new deck

### ISSUE THREAD

**Issue by mabos555** [cryogen/throneteki#1129]
it always says:
could not connect to the server please try later
i'm building my deck all the day and still nothing saved

**Comment by ystros** [comment]
Thanks for the report. Offhand I wasn't able to reproduce the issue, so it may be something specific to your setup.
* What web browser are you using and which version of it?
* Can you see errors in the developer console for your browser? (Varies between browsers, for Chrome at least you right click the page, click 'Inspect', which brings up the developer pane. Click the 'Console' tab, you potentially should see errors there)
* I saw you were able to enter chat messages into the lobby. Are you able to watch / spectate games on the site?

**Comment by mabos555** [comment]
1. i use chrome version 58.0.3029.110 (64 bit) i also tried it on my
Firefox and couldn't save my deck either
2. here is the result:
[image: Inline image 1]
3, yes i can see games, i played a game before accidentally deleted my
deck, now that i'm trying to create a new one it fails saving it

**Comment by cryogen** [comment]
Is this the one trying to save a really big deck?  Yeah that won't work currently, however I am refactoring the deck builder currently and big decks will work ok in that

**Comment by mabos555** [comment]
yeah i just got rid of a lot of characters and it fixed it ty
btw i have a question: when (if we will of course) will we be able to play
melee?
ty again for the help

**Comment by cryogen** [comment]
The deckbuilder changes have now been deployed so you can use your lots of characters deck now :)

as for melee.. it's possible but not in the 'soon' timeframe
