### ISSUE TITLE
lancel vs venomous blade

### ISSUE THREAD

**Issue by kitoxme** [cryogen/throneteki#1131]
can't target lancel lannister with v. blade, even though it says printed STR

**Comment by DukeTax** [comment]
Side note: Dacey and Beric possibly have the same issue.

**Comment by ystros** [comment]
This should actually be fixed with #1115, as currently the game is reading 0 STR characters as having 'undefined' strength. That PR makes it consistently return 0 for characters with 0, null and undefined strength.
