### ISSUE TITLE
The Tickler does not give an option to use his action

### ISSUE THREAD

**Issue by tne2008** [cryogen/throneteki#1141]
The Tickler should be able to kneel to force the opponent to discard on the Dominance phase. Without manually doing it, you can't.

**Comment by cryogen** [comment]
Click the green triangle here:

https://www.dropbox.com/s/63g2yffqxp4n2io/Screenshot%202017-07-10%2005.58.42.png?dl=0

click the dominance phase checkbox here:

https://www.dropbox.com/s/lvjyte0fbll87m0/Screenshot%202017-07-10%2005.59.20.png?dl=0

and you'll be prompted for actions in the dominance phase.

There are too many windows that do not always see use for the game to prompt every one, so only certain default ones are prompted unless you turn them on.  If you find yourself using certain windows frequently, you can set your own defaults in your user profile
