### ISSUE TITLE
Now My Watch Begins prompts when cards are placed in owner's discard pile

### ISSUE THREAD

**Issue by Fred-Byrd** [cryogen/throneteki#1159]
Instead of prompting only when cards enter an opponent's discard pile, Now My Watch Begins prompts when your own characters are discarded as well. Cost check still takes place.

Steps to reproduce: Start a game, and manually discard a character of cost 5 or lower from your hand while having the event and 2 gold available. The event can be played, and you will not take control of the character.

![image](https://user-images.githubusercontent.com/12630640/28147836-fb499c3c-6737-11e7-9510-ab9dc0836a6d.png)

**Comment by ystros** [comment]
Thanks for the report + detailed reproduction steps!
