### ISSUE TITLE
Second LOTCrossing challenge temporarily gives -1 STR

### ISSUE THREAD

**Issue by DukeTax** [cryogen/throneteki#1169]
There is a small window after declaring attackers and before the challenge counter gets updated. In that window the character gets Crossing's -1 STR and could then die for example to Blood of the Dragon.

First challenge with Tyrion, second with Tumblestone Knight:

```
DukeTax is initiating a  challenge
DukeTax uses Tyrion Lannister to gain 2 gold as an intrigue challenge has been declared
DukeTax has initiated a  challenge with strength 2
does not defend the challenge
DukeTax won a  challenge 2 vs 0
DukeTax has gained 1 power from an unopposed challenge
DukeTax is initiating a  challenge
Tumblestone Knight is killed as its STR is 0
DukeTax kills Tumblestone Knight
DukeTax has initiated a  challenge with strength 0
```

Edit: probably temporarily gives +2 STR on the 4th challenge as well.

**Comment by ystros** [comment]
Probably going to wait until #1162 is merged before attempting to fix this, as it will likely generate merge conflicts.
