### ISSUE TITLE
Players can still play copies of uniques if their opponent controls them

### ISSUE THREAD

**Issue by Fred-Byrd** [cryogen/throneteki#1170]
If an opponent takes control of a player's unique card, that player cannot play additional copies of that unique card. However, it is currently possible for the owner to play additional copies of the card which the opponent has taken.

Creates kind of an awkward situation since this rule isn't well known amongst casual players.

**Comment by ystros** [comment]
Thanks for the report! We do have code to check this rule, but apparently it isn't working anymore.
