### ISSUE TITLE
"Sea Bitch" offers selection of own locations instead of opponent when plundered with Euron

### ISSUE THREAD

**Issue by Xardas-T** [cryogen/throneteki#1199]
I had a game the other day where I was playing an GJ/Banner Lion deck against a Targ/Banner GJ deck. I was able to trigger Euron and steal the "Sea Bitch" location from my opponent's discard, who also had a copy of Iron Mines in play. After I stole it, I wanted to trigger its ability and also temporarily take control of his Iron Mine (he was about to attack and I could have used more saves on his claim of 2). The problem was that when I attempted to use "Sea Bitch", the only highlighted options were my own Iron Mines as well as my other locations (but not his). That doesn't make much sense to me unless the game considered "Sea Bitch" as still part of my opponent's controlled cards. Can you confirm for me that this is an issue? It really kills a nice combo that can be fairly useful especially when facing another GJ deck.

Thanks!!

**Comment by DukeTax** [comment]
Thanks for the detailed bug report. A fix is in, should be deployed in a couple of days most likely.

**Comment by Xardas-T** [comment]
That's awesome. Thanks a lot!
