### ISSUE TITLE
running out of draw cards should result in game loss

### ISSUE THREAD

**Issue by ploog** [cryogen/throneteki#1210]
Having no cards in your deck is not setup as win/loss condition (or if it is it isn't apparent).  I've had my opponents concede but it would be nice to make it automatic.  (Also if I could put a plug in for getting Taking the Black to be implemented that would be great-(no chance to trigger during dominance))

**Comment by DukeTax** [comment]
Getting decked should result in an immediate loss as well as chatmessage indicating it. Have you encountered a specific instance of that not happening?

Take the Black should work fine. Have you activated dominance actions, either as a default in your profile (top right of your screen) and/or during the game by clicking the green triangle above the Done-button?

**Comment by zacchiro** [comment]
I just checked, and this is indeed reproducible: running out of cards currently does not result in game loss. You will simply not draw any card from your deck in the draw phase, but the game continues normally.

(In passing: the easiest way to test this is currently /draw 60 + /discard 60 ; because /pillage doesn't support a numeric argument. It should :-))

**Comment by ploog** [comment]
Sorry for the delay in replying.  Real life plus forgetting to return is my excuse.  :)  Take the black does work just fine if dominance actions is turned on.  As zacchiro said, I'm not seeing any chat log for it (but maybe in the annals it is being recorded correctly, that I don't know)

**Comment by ystros** [comment]
Hmm. I can't actually reproduce this except in specifically single player games, where there's no clear concept of a winner or loser. Messaging should probably be updated to clarify that case though.

In the two player game this occurred in (if you can remember), was the last card drawn via draw phase, drawn via card ability, or pillaged?

**Comment by ploog** [comment]
It appeared to have been fixed at about time of last message
