### ISSUE TITLE
Ward + First Snow

### ISSUE THREAD

**Issue by IMABUNNEH** [cryogen/throneteki#1223]
Bit of a weird situation:

I played a character, my opponent used Ward to take control of that character.

I used First Snow, which returned that character to my hand (and discarded his Ward). All is as it should be.

I played the same character from hand, my opponent used a new Ward on the character. However the game would not give control of that character to my opponent. The Ward attached successfully but the character stayed on my side of the board, and was only able to be manipulated (challenges etc) by myself.

I attempted to use the /give-control command on the character, and the chat prompt confirmed I had done so but the character STILL didn't change control.

**Comment by DukeTax** [comment]
Possibly similar to #1065.

**Comment by ystros** [comment]
Definitely can reproduce this one. Thanks for the detailed scenario!
