### ISSUE TITLE
Lady in Waiting can dupe opponent's cards

### ISSUE THREAD

**Issue by IMABUNNEH** [cryogen/throneteki#1225]
I don't know if it's because it's programmed similar to Bodyguard, but when using Lady in Waiting as a dupe, it allows you to dupe your opponent's ladies.

However although it's legal to Bodyguard opponent's cards, you cannot dupe a character you do not own, so Lady in Waiting is illegal to use here. Also illegal to use it to dupe ladies you have stolen control of (as you don't own them).

**Comment by DukeTax** [comment]
Thanks for reporting. The duping mechanism already guards against this, it's LiW's prompt that doesn't restrict enough targets (unless you actually did use LiW to dupe an illegal character, which would be another bug). A fix to properly restrict the prompt is in.
