### ISSUE TITLE
Some card border highlights don't get removed, ever

### ISSUE THREAD

**Issue by mplain** [cryogen/throneteki#1244]
![1](https://user-images.githubusercontent.com/7605827/28584703-57bb275e-7176-11e7-85c5-6846fd3f28d9.png)

**Comment by zacchiro** [comment]
I've seen it happen as well, but never tried to narrow down the pattern that makes it happen.
@mplain: if you see it again, can you please let us know precisely when/how it happened? Having a full copy of the game log at the time would be a good start. TIA!

**Comment by mplain** [comment]
One scenario I'm pretty certain of: marshal Arianne, she'd highlighted as 'a card that entered play this round', then during challenges return her to hand - she stays highlighted indefinitely. But this is a part of the general problem of lasting effects not expiring when an affected card is returned to hand.

To think of it, this is probably also the case here with Cersei: she was put into play using Hear be Roar, then bounced back to hand with Tower of the Hand (...oooh! THAT's why's it's called 'Tower of the Hand'!), then discarded to reserve.

**Comment by DukeTax** [comment]
This specific Cersei wasn't returned with Tower, but was discarded through the expiration of Hear Me Roar's effect, but it probably makes no difference.
