### ISSUE TITLE
Suggestion: reverse the order of cards in discard/dead/removed piles

### ISSUE THREAD

**Issue by mplain** [cryogen/throneteki#1248]
When you click on a pile to see what's in there, the more recent cards are shown at the bottom (for both players). I'm thinking of it like Tetris: older cards on bottom, newer cards on top. Perhaps people would find this to be more intuitive?
![1](https://user-images.githubusercontent.com/7605827/28590617-6e1d1402-718b-11e7-8abe-f9b644929032.png)

**Comment by ystros** [comment]
Reversing the order would be more consistent with how it works with the draw deck as well - top-most card first, bottom-most card last.

**Comment by cryogen** [comment]
Done, I have no idea how I never noticed this was the case since day 1.  I always intended for it to be this way.  The oldest bug in throneteki is now fixed :)
