### ISSUE TITLE
Treachery should cancel effects after targets are chosen

### ISSUE THREAD

**Issue by mplain** [cryogen/throneteki#1249]
Choosing targets is not part of the resolving effect. Knowing targets affects decision making for the player holding Treachery.

**Comment by DukeTax** [comment]
There's two possibly separate issues here:

1. Targets are usually chosen before resolution, but there's quite a number of cards that are running older code where that isn't the case. They are slowly being converted.
2. With the way messaging is setup now, even when targets are chosen before resolution, the player deciding to play the cancel won't be notified of those targets yet. This should get fixed when we overhaul the messaging system. In the meantime this should be resolved via chat.

**Comment by DukeTax** [comment]
Closing this as 1. most if not all cards have been converted by now and 2. is taken care of by the referenced PR.
