### ISSUE TITLE
Burn effects cannot be saved

### ISSUE THREAD

**Issue by JalekZem** [cryogen/throneteki#1253]
First, this card appears to no longer be attaching to the targeted character and giving the +1 str when played but is still saving the character.

Secondly, the client is not giving the option for RftS to be played to save after Dracyrs! is played.  Per the FAQ, as the character now is STR 0+1 after Risen takes effect, they should be returned to play, with Risen attached.

**Comment by ystros** [comment]
I can't reproduce the issue with the card not attaching. If you were saving a Greyjoy character that does not allow attachments (e.g. Silence's Crew), then saving the character but not attaching is the proper behavior. The save happens every time, but it only attaches to characters that allow attachments. http://thronesdb.com/card/01081

The second problem is definitely an issue, though.

**Comment by cryogen** [comment]
Burn effects are implemented as cannotBeSaved: true, it was always a known limitation but undocumented.. until now :)
