### ISSUE TITLE
"Leave Game" button should not prompt for the last player leaving

### ISSUE THREAD

**Issue by ystros** [cryogen/throneteki#1258]
Currently, if your opponent leaves the game without either player winning or conceding, you will receive a confirmation dialog saying the game is not "finished". However, if you're the last player in the game there is no real way to win at that point. Thus, that player should not have to confirm that they want to leave the game.

**Comment by cryogen** [comment]
Huh. This used to work so is actually a bug. I suspect the fix to disconnect the game server on leave has broken it
