### ISSUE TITLE
Error in messages.jsx on line 45

### ISSUE THREAD

**Issue by mattgrosso** [cryogen/throneteki#126]
Getting a game breaking error in console saying:

'Messages.jsx:45 Uncaught TypeError: Cannot read property 'code' of null(…)'

The stack trace is really long but here it is anyway.

(anonymous function)	@	Messages.jsx:45
w.map.w.collect	@	underscore.js:172
value	@	Messages.jsx:44
(anonymous function)	@	Messages.jsx:36
w.map.w.collect	@	underscore.js:172
value	@	Messages.jsx:35
value	@	Messages.jsx:74
_renderValidatedComponentWithoutOwnerOrContext	@	ReactCompositeComponent.js:796
_renderValidatedComponent	@	ReactCompositeComponent.js:819
_updateRenderedComponent	@	ReactCompositeComponent.js:743
_performComponentUpdate	@	ReactCompositeComponent.js:721
updateComponent	@	ReactCompositeComponent.js:642
receiveComponent	@	ReactCompositeComponent.js:544
receiveComponent	@	ReactReconciler.js:126
_updateRenderedComponent	@	ReactCompositeComponent.js:751
_performComponentUpdate	@	ReactCompositeComponent.js:721
updateComponent	@	ReactCompositeComponent.js:642
receiveComponent	@	ReactCompositeComponent.js:544
receiveComponent	@	ReactReconciler.js:126
updateChildren	@	ReactChildReconciler.js:110
_reconcilerUpdateChildren	@	ReactMultiChild.js:215
_updateChildren	@	ReactMultiChild.js:314
updateChildren	@	ReactMultiChild.js:301
_updateDOMChildren	@	ReactDOMComponent.js:942
updateComponent	@	ReactDOMComponent.js:760
receiveComponent	@	ReactDOMComponent.js:718
receiveComponent	@	ReactReconciler.js:126
updateChildren	@	ReactChildReconciler.js:110
_reconcilerUpdateChildren	@	ReactMultiChild.js:215
_updateChildren	@	ReactMultiChild.js:314
updateChildren	@	ReactMultiChild.js:301
_updateDOMChildren	@	ReactDOMComponent.js:942
updateComponent	@	ReactDOMComponent.js:760
receiveComponent	@	ReactDOMComponent.js:718
receiveComponent	@	ReactReconciler.js:126
updateChildren	@	ReactChildReconciler.js:110
_reconcilerUpdateChildren	@	ReactMultiChild.js:215
_updateChildren	@	ReactMultiChild.js:314
updateChildren	@	ReactMultiChild.js:301
_updateDOMChildren	@	ReactDOMComponent.js:942
updateComponent	@	ReactDOMComponent.js:760
receiveComponent	@	ReactDOMComponent.js:718
receiveComponent	@	ReactReconciler.js:126
updateChildren	@	ReactChildReconciler.js:110
_reconcilerUpdateChildren	@	ReactMultiChild.js:215
_updateChildren	@	ReactMultiChild.js:314
updateChildren	@	ReactMultiChild.js:301
_updateDOMChildren	@	ReactDOMComponent.js:942
updateComponent	@	ReactDOMComponent.js:760
receiveComponent	@	ReactDOMComponent.js:718
receiveComponent	@	ReactReconciler.js:126
_updateRenderedComponent	@	ReactCompositeComponent.js:751
_performComponentUpdate	@	ReactCompositeComponent.js:721
updateComponent	@	ReactCompositeComponent.js:642
receiveComponent	@	ReactCompositeComponent.js:544
receiveComponent	@	ReactReconciler.js:126
_updateRenderedComponent	@	ReactCompositeComponent.js:751
_performComponentUpdate	@	ReactCompositeComponent.js:721
updateComponent	@	ReactCompositeComponent.js:642
performUpdateIfNecessary	@	ReactCompositeComponent.js:558
performUpdateIfNecessary	@	ReactReconciler.js:158
l	@	ReactUpdates.js:151
perform	@	Transaction.js:138
perform	@	Transaction.js:138
perform	@	ReactUpdates.js:90
E	@	ReactUpdates.js:173
closeAll	@	Transaction.js:204
perform	@	Transaction.js:151
batchedUpdates	@	ReactDefaultBatchingStrategy.js:63
s	@	ReactUpdates.js:201
o	@	ReactUpdateQueue.js:25
enqueueSetState	@	ReactUpdateQueue.js:210
o.setState	@	ReactComponent.js:64
l.handleChange	@	connect.js:301
u	@	createStore.js:186
(anonymous function)	@	index.js:14
(anonymous function)	@	bindActionCreators.js:7
(anonymous function)	@	Application.jsx:89
n.emit	@	index.js:131
o.onevent	@	socket.js:270
o.onpacket	@	socket.js:228
(anonymous function)	@	index.js:21
n.emit	@	index.js:131
o.ondecoded	@	manager.js:332
(anonymous function)	@	index.js:21
n.emit	@	index.js:134
a.add	@	index.js:246
o.ondata	@	manager.js:322
(anonymous function)	@	index.js:21
n.emit	@	index.js:134
o.onPacket	@	socket.js:444
(anonymous function)	@	socket.js:261
n.emit	@	index.js:134
o.onPacket	@	transport.js:143
o.onData	@	transport.js:135
ws.onmessage	@	websocket.js:135

**Comment by cryogen** [comment]
Pretty sure this was fixed in 9757a3cb1ca4c9d143be8b308fdf4ef90aea268c

Reopen if not
