### ISSUE TITLE
password prompt is out of screen when trying to spectate old games

### ISSUE THREAD

**Issue by mplain** [cryogen/throneteki#1265]
When I want to spectate a game that's in the lower part of the list of ongoing games (started a while ago), I press Watch, and nothing seem to happen. I now need to scroll up to the top of the page, to see the field to enter a password. Suggestion: when a user tries to join/watch a private game, either make the screen jump to the beginning of the list (top of the page), or make the passowrd field 'stick' to the top of the screen.

**Comment by cryogen** [comment]
Thanks for documenting this, I keep meaning to fix it but it getting around to it

**Comment by cryogen** [comment]
This is no longer an issue as the game list scrolls and so the password box is pinned to the top
