### ISSUE TITLE
Suggestion: Timer feature (updated)

### ISSUE THREAD

**Issue by mplain** [cryogen/throneteki#1266]
So the timer is there mostly for The Hand's Judgment, Treachery, and Vengeance for Elia to work. But it seems to encumber the overall game experience a lot. So, suggestions:

1) Add an option to user settings: "Prompt timer for events only" (default) -vs- "Prompt timer for all triggered abilities", and let Lannister players enable the latter option for themselves if they want (or auto-enable it whenever a player loads a deck with House Lannister or Banner of the Lion).

2) Option: Skip the timer prompt if the player cannot possibly play The Hand's Judgment (has less gold in his gold pool that the printed cost of the played event, factoring in discounts) or Treachery (doesn't have 1 gold and a unique Lannister character in play).

3) Show the card image of the event being played in the timer prompt. This would create the feeling of "give me a moment to read this card" instead of "let me think whether I want to cancel this event", which I think should improve the overall game experience.

**Comment by cryogen** [comment]
The last of the refinements to the timer was just merged in b4ee4a6b65a1e8296eea45fa3b7d719807f74cff
