### ISSUE TITLE
Calm over Westeros -vs- The Rains of Castamere

### ISSUE THREAD

**Issue by mplain** [cryogen/throneteki#1267]
Player A reveals Calm over Westeros, names military. Then, triggers Castamere and reveals a new plot.
Player B wins military, his claim is still reduced to 0.

**Calm Over Westeros**
When Revealed: Name a challenge type. *Until you reveal a new plot card*, reduce the claim value on the attacking player's revealed plot card by 1 during challenges of that type in which you are the defending player.

The effect lasts until Calm is replaced by another plot, not until the next plot phase.

**Comment by DukeTax** [comment]
Thanks for reporting.
