### ISSUE TITLE
Suggestion: color the Latest Site News in red/green/blue

### ISSUE THREAD

**Issue by mplain** [cryogen/throneteki#1269]
I get a feeling that many users don't read the News block on the main page. They don't read it on purpose, and they don't notice any changes.

You cycle icons (mil-int-pow) for each piece of news. This is a good idea, but I think this is not enough to catch the users' attention.

Suggestion: not only cycle the icons, but also color the topmost news in the corresponding color and in bold font. So, today the topmost news is in bold red with a mil icon. Tomorrow the topmost news is in bold green with an int icon. And the one below it (that was the topmost today, with a mil icon) is in plain letters (no color, no bold).

This way it'll catch the eye - users will notice that something is diffferent, and stop to read about the update - not just complain that something is new and they cannot figure out how it works.

**Comment by cryogen** [comment]
Happy to restyle the news (the whole main page needs restyling), but it won't make people ready stuff any more than they do now. (the amount of people running old client code despite the big red prompt telling you to update is staggering)

**Comment by cryogen** [comment]
Been playing with this, can't get it to look quite right:

https://www.dropbox.com/s/4at3un4wl704uu3/Screenshot%202017-07-29%2008.22.50.png?dl=0

**Comment by mplain** [comment]
I thought of coloring the text (not the background) and making it bold, and removing the color and boldness on any news that is not the topmost.

**Comment by cryogen** [comment]
Something like this:

![screenshot 2017-07-29 10 05 44](https://user-images.githubusercontent.com/1053365/28743613-a5d7efae-7445-11e7-9726-92f07c7bda36.png) ?

The transparency will need tweaking to fit with the new style but don't worry about that

**Comment by mplain** [comment]
Well the first one is definitely more readable :)

I'll ask my wife for advice, she's a web interface designer 'n all.

**Comment by cryogen** [comment]
It looks better after the transparency is adjusted, not overly sure about the blue, though.

**Comment by cryogen** [comment]
The new site design is now live and incorporates this suggestion

**Comment by mplain** [comment]
The current color pallette is very hard to read, green text on a dark background. I suggest using a lighter background, readability over aesthetics.

Also, my suggestion was to color only the single one most recent news (the topmost). If you use red+green+blue together all the time, the users won't notice the switch in their order. If only the topmost news is colored, and the ones below it are in black (on a light background, of white on a dark background), then they will instinctively notice something is different (i hope).

Also you're currently using green text for both INT and POW news.

![1](https://user-images.githubusercontent.com/7605827/29156959-261471d6-7dad-11e7-8d00-262495fbf64b.png)

**Comment by cryogen** [comment]
> The current color pallette is very hard to read, green text on a dark background. I suggest using a lighter background, readability over aesthetics.

I think it's fine, honestly. It depends on your screen size and the text but sometimes some words can be a bit dominated by the background, but overall I think it's fine.  The transparency can be reviewed if it's an issue.

> Also, my suggestion was to color only the single one most recent news (the topmost). If you use red+green+blue together all the time, the users won't notice the switch in their order.

That's what I've done, see:
> Also you're currently using green text for both INT and POW news.

That's intended, as above.

**Comment by mplain** [comment]
So when the topmost news has an INT icon, all the text will be in green?

**Comment by cryogen** [comment]
No, the icons stay in the same order, top most is always mil/red/bold

**Comment by mplain** [comment]
This goes contrary to my idea to bring the users' attention by changing the color of the topmost news. But oh well.

**Comment by cryogen** [comment]
Looks like I've misunderstood what you meant.  Sorry about that.  I'll think on this some more.
