### ISSUE TITLE
Suggestion: Expand the "green triangle" settings

### ISSUE THREAD

**Issue by mplain** [cryogen/throneteki#1270]
1. Switching the timer settings in the user profile doesn't apply to the current game, only to subsequently created games. Suggest adding timer settings to the "green triangle" menu.

2. Change the "green triangle" to a standard-looking "settings" icon (e.g. a cog and a screwdriver), so that people will intuitively recognize it for what it is.

**Comment by cryogen** [comment]
This is done now.  All except the timer slider, just because that's a pain to do at the moment, it may come later.
