### ISSUE TITLE
Ours is the Fury bug

### ISSUE THREAD

**Issue by ChannelDelibird** [cryogen/throneteki#1273]
Just noticed an issue with Ours is the Fury. My opponent used it to target a Stannis Baratheon who was already participating in the challenge as a defender - this is a legal play because he could potentially stand upon winning the challenge - but Throneteki counted his STR twice when we resolved the challenge because it thought there were two instances of him participating in the challenge.

**Comment by cryogen** [comment]
Oh goodie, we haven’t had a double str bug in ages 🙂

Thanks for reporting
