### ISSUE TITLE
Cannot discard cards in discard phase

### ISSUE THREAD

**Issue by monto01** [cryogen/throneteki#1281]
Hi :)

recently i encountered an issue in the discard phase where i cannot put my cards from my hand to the discard pile. When this issue occours I'm unable to pick cards and move them to any play areas. Im using firefox at the latest version.

**Comment by cryogen** [comment]
Hi!

Firefox has a bug where it occasionally likes to forget how to drag/drop.

Due to the relatively small number of people using firefox I haven't explored this too much, but I will eventually.

Suggestion for the mean time is to use another browser

**Comment by cryogen** [comment]
This should no longer be an issue as the reserve prompt now asks you to pick cards, rather than drag them
