### ISSUE TITLE
Dolorous Edd can be selected as a defender for double his STR

### ISSUE THREAD

**Issue by mplain** [cryogen/throneteki#1285]
Use Edd's ability to put him into play + select him as a defender = double his STR.

![1](https://user-images.githubusercontent.com/7605827/28849871-e2504592-7721-11e7-880f-63e913614b6f.png)

**Comment by DukeTax** [comment]
@cryogen Still want to fix this stuff on the cards itself instead of on challenge? :P

**Comment by DukeTax** [comment]
Thanks for reporting.
