### ISSUE TITLE
Manually standing cards does not remove them from the challenge

### ISSUE THREAD

**Issue by cryogen** [cryogen/throneteki#13]

**Comment by DukeTax** [comment]
Should manually standing cards remove them from the challenge though? Challenge participation and standing/kneeling are very much separate things in Thrones, and with all kinds of stand effects not implemented yet this is probably a good thing.

**Comment by cryogen** [comment]
This was asked for a long time ago, but noone's really asked since.  I'm gonna close it as I think I agree with you, although there doesnt currently exist a way to remove a card from a challenge
