### ISSUE TITLE
Pillage Tywin's reaction

### ISSUE THREAD

**Issue by samuellinde** [cryogen/throneteki#132]
Tywin Lannister's (05006) pillage interrupt is very clunky to handle manually, since his pillage keyword triggers automatically. I don't know if there's a mechanism for showing cards to your opponent, but that would probably be necessary.

**Comment by CourteousCorsair** [comment]
soo 

Tywin's ability works with pillage, Loot, The Tickler, and Jojen Reed. If Jojen makes each player discard the top card of the deck, Tywin will trigger once for each player.

It will looks like :

 For the pillage function =>{
If Tywinn lotr (ID card) in play AND no milk attach
Do ; Scry 2 }
;

**Comment by cryogen** [comment]
This just hasn't been implemented yet
