### ISSUE TITLE
"Until end of Phase" vs. returning to hand

### ISSUE THREAD

**Issue by davedavedavedavedavedave** [cryogen/throneteki#1321]
1. Ambush Burned Men.
2. Give them INT Icon with Mountains of the Moon.
3. Return them to hand with Tyrion.
4. Ambush them again.
= They still have the INT Icon, even though they shouldn't.

Similar issue with Harrenhal:
1. Put Burned Men into play with Harrenhal.
2. Return them to hand with Tyrion.
3. Ambush them again.
= They will be killed at end of phase, even though they shouldn't.

It looks like "until end of phase" effects are not reset when cards are returned to hand.

**Comment by ystros** [comment]
Thanks for reporting! This seems to be a general problem with lasting effects not reseting when a card leaves play. See also #844.
