### ISSUE TITLE
Apply conditional bonuses/effects

### ISSUE THREAD

**Issue by samuellinde** [cryogen/throneteki#134]
Two cases:

- Hedge Knight should gain a power icon (and +1 STR) while you control another Knight. No big deal to remember if it wasn't for the fact that he can't participate in power challenges without his icon.
- Knight of Summer (04023) gets renown and +2 STR while there are more Summer than Winter plots revealed.

**Comment by doomnote** [comment]
You can apply strength bonuses using "/strength x" where x is the total strength the character should have. Cards are being implemented individually so not every card does it's text automatically yet.

**Comment by samuellinde** [comment]
Yeah, I know that, I reset the STR manually. But since SoS is partially implemented I thought it would be good to track this issue. When it enters the used pile, it should reset the STR, I think.

**Comment by samuellinde** [comment]
Sure, adding STR manually is fine. Maybe there should be a command for manually adding icons to characters (temporarily)? That would help Nymeria work etc. As it is now, characters can't participate in challenges if they lack the proper icons (as far as I can tell from testing).

**Comment by doomnote** [comment]
That's the plan

**Comment by Vicaroth** [comment]
Yeah the bigger issue is Hedge Knight cannot use the power icon. Would be awesome just to have a way to add an icon manually for now.

**Comment by cryogen** [comment]
most of the cards mentioned in this thread are implemented now so i'm going to close this issue
