### ISSUE TITLE
Mirri cannot trigger her interrupt after attacking with The Hound

### ISSUE THREAD

**Issue by atkeranov** [cryogen/throneteki#1341]
1. Attack with both Mirri Maz Duur and The Hound in a single challenge.
2. Win the challenge and return The Hound to your hand.
3. Apply claim.

Unexpected: cannot trigger Mirri's interrupt to replace the claim effect.
Expected: Mirri should be able to trigger her interrupt. This is explained in detail in http://thronesdb.com/find?q=mirri section "Rules FAQ pt 2"

**Comment by ystros** [comment]
Thanks for the report + detailed steps to reproduce!
