### ISSUE TITLE
Nightmares + Limited + (Dagmer/Newly Made Lord)

### ISSUE THREAD

**Issue by 03omcdonnell** [cryogen/throneteki#1345]
Hi there,

When you use Nightmares on a Limited Location the Limited keyword is blanked. This should allow it to be targeted by effects that would normally work only on non-limited locations. e.g. Newly-Made Lord and Dagmer Cleftjaw (See comment from https://thronesdb.com/card/02111 )

I've run into a couple of issues with Nightmares not properly blanking limited cards.

1. Use Nightmares on a Limited location.
2. Marshal Newly-Made Lord and use his reaction.
Issue: Cannot select the Limited location from step 1.

The same applies to Dagmer Cleftjaw's ability.

This also looks like it might apply to Nightmares + 'Frozen Solid' and Nightmares + 'Raiding the Bay of Ice', not been able to test properly.

It looks like the !card.isLimited condition used to check targets is checking this.hasKeyword('Limited') OR this.hasPrintedKeyword('Limited'). It looks like this.hasPrintedKeyword('Limited') is an invalid condition for the above effects.

I would propose updating the !card.isLimited condition to !card.hasKeyword('Limited') in the above cases. I believe this is already the current implementation for Sea Bitch.

Thanks,
Oli

**Comment by DukeTax** [comment]
Thanks for the high-quality bug report.
