### ISSUE TITLE
Randyll Tarly Limit 3?

### ISSUE THREAD

**Issue by DisturbedMikey1** [cryogen/throneteki#1349]
Looking at my Decks, my Hot Summer Knights Tyrell deck is labeled as invalid because "Randyll Tarly has limit 3." What does that mean and why is it a thing. Thanks very much.

**Comment by cryogen** [comment]
It's telling you that you have more than 3 copies of Randyll Tarly in your deck. If this is not the case, please post the decklist and i'll take a look
