### ISSUE TITLE
Unable to Choose Red Cloaks for Attachment

### ISSUE THREAD

**Issue by doomnote** [cryogen/throneteki#135]
Trying to marshal a Fishing Net on Red Cloaks - clicking on Red Cloaks just brings up its submenu but won't let it be chosen.

**Comment by cryogen** [comment]
Did the submenu have 'select' on it, and does clicking this let you attach?

**Comment by doomnote** [comment]
Ah it might have - it was behind the other cards so I couldn't see it (wrong layer).

**Comment by cryogen** [comment]
Yeah that option will do what you want.  The display issue is annoying and I can't seem to track it down.  It's really inconsistent too as the draw deck has the same menu styling but appears above cards.  Go figure.

**Comment by doomnote** [comment]
The real issue here is the submenu layering so I'm closing this.
