### ISSUE TITLE
control of characters and associated issues

### ISSUE THREAD

**Issue by Redal59** [cryogen/throneteki#1351]
Since building and testing with a NW/Wolf deck utilising a lot of the character stealing tech I've noticed there are more than a few bugs still to be ironed out. 

Often characters that are Ward'd or stolen with Yoren or Night's Watch Recruiter, when they are subsequently discarded or killed they can end up in the discard/dead pile of the person who stole them rather than their original owner. 

Also while trying to use Frozen Solid, it won't allow you to choose a limited location even after you blank it with Nightmares. 

Finally triggers for cards like Bastard Daughter, Robb Stark and Viserys Targaryen are all still being given to the original owner of even after characters stolen by the opponent have been killed or sacrificed.

**Comment by DukeTax** [comment]
Thanks for reporting. The issue with Frozen Solid/Nightmares has been resolved and will be deployed soon. :)

**Comment by ystros** [comment]
I think all of these issues have been resolved. Please reopen / open a new issue if that's not the case. Thanks!
