### ISSUE TITLE
kicked out spectator still seed old game

### ISSUE THREAD

**Issue by xarathornx** [cryogen/throneteki#1361]
Join a game as a spectator...when both players leave the game...the spectator gets back to the lobby...fine...but the next game he joins or creates...he either sees the old gamescreen or if he sees the new game he just joined but after a couple of minutes the screen changes to the old game.... logging out and in alone does not help...closing the browser is necessary as well

**Comment by cryogen** [comment]
Fixed in 324a8967baa580d954f4dd2d5bd8a595903290dc
