### ISSUE TITLE
Wilding scout ability after entering play through Flea Bottom

### ISSUE THREAD

**Issue by idealspleen** [cryogen/throneteki#1364]
Hi there,
the ability of the wildling scout (sacrifice him to give stealth to a character) usually does not work when he is been put in play through flea bottom.

thanks for your great work!

**Comment by ystros** [comment]
Thanks for the report! Wildling Scout was improperly implemented with a limit once per phase restriction, so if you sacrificed it, brought it back into play with Flea Bottom, then tried to sacrifice it again it wouldn't work. The limit should be reset when cards leave play but there's a separate bug about that (#1098)
