### ISSUE TITLE
Marya Seaworth reaction does not trigger twice in a challenge?

### ISSUE THREAD

**Issue by idealspleen** [cryogen/throneteki#1383]
Hi there,
Going into my first challenge with two char having stealth, and marya on the  board, I could see the two buttons for her trigger but once I clicked on one trigger and chose the char to kneel, the second trigger button for the other char would not appear. I had sufficient spare gold left I if remember correct.

what do you think?
thanks

**Comment by cryogen** [comment]
This was literally fixed last night in #1380.  Thanks for the report! The fix will be deployed some time this week.
