### ISSUE TITLE
allow to manually change the active plot

### ISSUE THREAD

**Issue by JoshuaWalker48** [cryogen/throneteki#1388]
I was playing thrones today whilst talking with a buddy of mine on discord. I thought Valar would be the best plot to play, so I chose it, but as soon as I chose it, I realized it wasn't the plot I wanted to play. So I told my friend to hold on a second because it wasn't the plot I wanted to play, and he said okay, but unfortunately I couldn't change it, even though plots hadn't been revealed yet. Seriously, this needs to be changed. You should be able to change your plot before you reveal them. That inability to change plots before they were revealed, lost the game for me.

**Comment by zacchiro** [comment]
So, this is what I was fiddling with the other day, when I discovered that one can duplicate a plot card by dragging & dropping the currently active plot back to the plot deck :-)

This request makes sense, as it's one of the very few cases (maybe even the only one?) where one cannot manually work around game automation.

**Comment by cryogen** [comment]
FYI I'm implementing this as originally reported and not as amended by @zacchiro, sorry :)

**Comment by zacchiro** [comment]
@cryogen sure, no problem of course.
Would you be opposed to having a separate issue opened for the title I suggested? It's a different feature and a needed one IMHO.
