### ISSUE TITLE
Crown of Gold + Daenerys

### ISSUE THREAD

**Issue by Martozar** [cryogen/throneteki#1411]
When a 4 STR character with Crown of Gold (so has -4 STR), which was saved by Risen from the Sea after CoG was played, participating in challange againts opponent with standing Daenerys and got -1 STR, his total STR is 0 but he is not killed, but should be because of CoG text.

**Comment by zacchiro** [comment]
As a Targ player I'm pretty sure Crown + Daenarys works as expected. So in your case there might have been an additional reason that made it fail.

Can you give us more details about the exact situation in which this happened?

**Comment by Martozar** [comment]
During marshalling phase I had Asha Greyjoy, an opponent played Crown of Gold on her and I saved her with Risen from the Sea, so she had 1 STR. In challenge phase during the same round I initiated pow challenge, but forgot about Dany's modifier. So, Asha's STR was changed to 0, but she didn't die, but suposed to, I think, because she still had Crown attached.

**Comment by cryogen** [comment]
Pretty sure this is/is related to #1319

**Comment by zacchiro** [comment]
Now that #1319, this should be fixed too (and it hadn't ever been reproduced up to now anyway).
Please reopen if you reencounter this in the wild.
