### ISSUE TITLE
Plot Clash of Kings reaction do not declare on defense?

### ISSUE THREAD

**Issue by idealspleen** [cryogen/throneteki#1419]
I was first player, and after I triggered clash of kings reaction on my turn, I won on defense my opponent power chall, but the clash of kings trigger did not triggered the second time.

Any clues?

thank you

**Comment by DukeTax** [comment]
The implementation looks good, so maybe something else prevented a trigger. Was Catelyn Stark in the challenge? Winterfell active? Did you opponent even have power to steal?

**Comment by idealspleen** [comment]
Opponent was playing NW agenda kings of winter, he had power on his faction card. He made the power challenge with a veteran builder brought by Flea bottom (first or second time during the round, cannot remember) and I opposed it with two characters.

**Comment by mplain** [comment]
Close this as unreproduceable?
