### ISSUE TITLE
Brothel Madame and A Game of Thrones plot

### ISSUE THREAD

**Issue by TerryKatsoulis** [cryogen/throneteki#1434]
So I was playing as the Lannisters and i chose the A Game of Thrones plot which states that you cannot initiate a military or power challenge until you win an intrigue challenge. When the brothel madame triggered my opponent to pay a gold in order to be able to do military challenges, they chose to pay it. Then, when the challenges phase began, my opponent (by accident) initiated a military challenge while not having won an intrigue challenge to be able to do so as per the plot. Just letting you know, so that you can look into it. Thank you and keep up the great work!

**Comment by ystros** [comment]
Thanks for the report! Looking at the code, it will undo any "cannot initiate challenge" effects if two are in play (in this example Brothel Madame and A Game of Thrones) and one expires (e.g. after Brothel Madame is paid), which is definitely a bug.
