### ISSUE TITLE
Misfuction when applying a 2 military claim when you only have a character.

### ISSUE THREAD

**Issue by fafranco82** [cryogen/throneteki#1445]
I was defending a military challenge, with claim value of 2. My only character was Asha, and I had 2 Iron Mines...

I chose not to defend the challenge, chose Asha por military claim and use a Iron mine to save her. But after that, the game asked me again to save Asha with the other mine or pass and kill her... It's like the claim 2 was applied sequentally, but targets for claim are choose and then killed simultaneously, so having only 1 character in play, I only have to save it once, no twice...

**Comment by zacchiro** [comment]
Thanks for your bug report! After testing I'm closing it as non reproducible for now though.

My test has been as follows. Military claim 2 against a board with only Victarion (without power on him) and 2 Iron Mines. I've been prompted to pick 2 characters for claim, and I picked only one. After that, I've been prompted on how to save him, with a dialog box with 3 options: 1 for each Iron Mine + done (to avoid saving). After saving him with one Iron Mine, the dialog box went away, and Victarion remained on table.

If you have a way to reproduce this again, or more info on how to do so, please reopen.

**Comment by fafranco82** [comment]
Ok, thanks!!

It was an old issue, maybe was already fixed in an earlier commit.
