### ISSUE TITLE
The Wall

### ISSUE THREAD

**Issue by tlaunay** [cryogen/throneteki#145]
The original issue https://github.com/cryogen/throneteki/issues/139 was closed after https://github.com/cryogen/throneteki/commit/ba44633dec2ca68c87197263b7654098b16389ee but it was not fixed.

- When a duped The Wall is knelt, a prompt to trigger it at the end of the challenge phase is still shown (not sure the duplicate is responsible for this but that was the situation).

- A duped Wall will also auto-provide its boost twice (and maybe thrice if there's a triplicate).

Related suggestion: add a menu to the Wall, where you can add/remove the +1 to all NW characters in play on the right side of the board? (especially useful for Nightmares)

**Comment by cryogen** [comment]
The fix is not deployed yet :)

**Comment by tlaunay** [comment]
Ah I thought it had been committed into master already? I need to learn how to read Github right, apologies!

**Comment by cryogen** [comment]
It has, but the server needs to be restarted to get the latest code

**Comment by cryogen** [comment]
Server now has the latest code
