### ISSUE TITLE
Could not communicate with the server.

### ISSUE THREAD

**Issue by Toomagic** [cryogen/throneteki#1455]
Hello ! Whenever I try to connect (at 3 differents places with 3 differents PCs...) I have this error message popping after trying to login : "Could not communicate with the server. Please try again later.".
The console states this message :
"JQMIGRATE: Migrate is installed with logging active, version 3.0.0  bundle.min.js:63:377
downloadable font: maxp: bad max_zones: 0 (font-family: "agot" style:normal weight:normal stretch:normal src index:0) source: https://www.theironthrone.net/fonts/agot.ttf  www.theironthrone.net:5:316373"

**Comment by cryogen** [comment]
Odd, you somehow ended up in the users table twice, once without a password set.  Fixed now, you should be able to login.

**Comment by Toomagic** [comment]
Thanks a lot ! I'm really good at getting weird bug, just wednesday I did an SQL request and my variable was empty instead of the string of the request... I re-wrote the code twice, and had a teacher come to check my code and... Nothing... Just empty ><"
