### ISSUE TITLE
treacheried abilities can bypass repetition limits

### ISSUE THREAD

**Issue by zacchiro** [cryogen/throneteki#1461]
Happened to me yesterday playing Stark against Lannister:
- character is sacrificed, I trigger Robb Stark to stand the board
- Robb's effect is canceled with Treachery
- later on in the same round a character dies, I'm asked (and managed to) trigger Robb again whereas I shouldn't have been able to

**Comment by idealspleen** [comment]
Indeed, had the same issue with Mel reaction, the AI allowed me to trigger it a second time even though the first instance had been treacheried.
