### ISSUE TITLE
Can't Load Deck

### ISSUE THREAD

**Issue by benelgermosen** [cryogen/throneteki#1473]
I used the block list to block someone and I'm getting a "Loading Deck From Server" message.

**Comment by cryogen** [comment]
Presumably you've tried refreshing your browser?  If you press f12 are there any errors in the console window?

**Comment by benelgermosen** [comment]
Yeah. I tinkered around with my cookies and was able to get back to working


On Sep 21, 2017 3:25 AM, "Stuart Walsh" <notifications@github.com> wrote:

Presumably you've tried refreshing your browser? If you press f12 are there
any errors in the console window?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cryogen/throneteki/issues/1473#issuecomment-331074681>,
or mute the thread
