### ISSUE TITLE
Double Winterfell, and Cat triggering from discard

### ISSUE THREAD

**Issue by mavric2205** [cryogen/throneteki#148]
Hey guys,
 Just wanted to bring an issue up I encountered in my last game in case you are unaware. I played Winterfell with a duplicate on it and when I marshaled Stark characters they were getting +2 STR as if I had two separate Winterfells in play. I tried moving one to the discard pile and just remembering about the dupe but it was still doing it.  In addition, during the game I killed a stark character and my Catelyn Stark(WotN) was in the discard pile and it asked me if I would like to trigger her ability to give herself a power. Again both not hugely important issues and easily worked around manually but wanted to make you all aware. Thanks for all the hard work in making this site, great job so far and only getting better every time I play.

**Comment by cryogen** [comment]
Fixed in c468319eedd1785d7287e0a4395578153e34c51c
