### ISSUE TITLE
pay the iron price does not allow greyjoy player to place attachment on opponent's character

### ISSUE THREAD

**Issue by wj6527** [cryogen/throneteki#1485]
nt

**Comment by DukeTax** [comment]
Thanks for reporting. Which attachment have you tried it with?

**Comment by wj6527** [comment]
The Martell icon removal ones. Like I couldn't put Attainted on his char. Maybe it's because those don't say opponent's character only.

**Comment by DukeTax** [comment]
To anyone tackling this issue: the likely problem is that the attachment.canAttach check happens while the card is still in the opponent's discard pile. This means that attachments that can only go on opponent's characters (like the Martell icon strippers) can only be attached to your own character, and probably, vice versa (like Venomous Blade only going on opponent's characters).
