### ISSUE TITLE
cannot play risen from the sea from discard when annals is flipped on valar

### ISSUE THREAD

**Issue by wj6527** [cryogen/throneteki#1488]
nt

**Comment by wj6527** [comment]
it actually happened again, 2 games in a row, and in the second one it worked (i was able to save with a risen from my discard)..... so not sure what's going on. sorry if this ends up being some sort of mistake on my part, ignore if so

**Comment by ystros** [comment]
Do you remember any difference between the two games? (e.g. you created the game vs joined an existing game, you were first player vs not, etc)

**Comment by wj6527** [comment]
No, I do not..... both of those are possibilities.

**Comment by ystros** [comment]
I suspect this was related to #1591, which has been fixed since. Re-open / open a new issue if it happens again.
