### ISSUE TITLE
enhancement: non-color coded clues about the meaning of various counters

### ISSUE THREAD

**Issue by zacchiro** [cryogen/throneteki#149]
Currently, the various counters associated to each card in play (number of duplicates, modified strength, etc.) are distinguishable only based on the color of the counter box (red, green, blue, etc.).
That's suboptimal in terms of accessibility (e.g., various forms of color blindness), but also makes it harder for throneteki newcomers to figure out what's going on.

It would be nice to have additional, non-color-coded clues about the meaning of the various counters. A simply possibility would be a hover tooltip on the counter boxes.

Alternatively, one might add a color-legend somewhere, but that will have at least two drawbacks: a) won't help with accessibility, b) it will consume screen estate.

With many thanks for Throneteki, it's an awesome project!

**Comment by cryogen** [comment]
I haven't forgotten about this, I'm just not overly sure how to do it, quite yet
