### ISSUE TITLE
Enchantments 

### ISSUE THREAD

**Issue by uBaHoB** [cryogen/throneteki#15]
Here is a list of things we talked about

1. Discard Random card Button
2. Look at top X
3. Action Windows:
 -Before Challenges
 -Before declare defenders
 -After declare defenders
4. Take control effects: Ward, Taking the Black, The Night Gathers ...
5. Faction Card Kneel

Cheers,
Ivan (uBaH)

P.S. Not everything needs to be automated. Dominance, Reserve prompt, Counting income are good beginning.

**Comment by cryogen** [comment]
1. is done now, /discard

**Comment by cryogen** [comment]
As most of these are now implemented in some fashion, I'm closing this issue
