### ISSUE TITLE
Keep getting blocked players in my lobbies

### ISSUE THREAD

**Issue by brandonpittman** [cryogen/throneteki#1505]
I'll see the already created lobby drop back to the list of games, I'll recreate a new one and then I'll see people on my block list show up in my game.

**Comment by ystros** [comment]
Thanks for the report! A question to help track down the issue - are the people joining people that you've just blocked (e.g. play a game, block that user, immediately start a new game, the blocked user joins), or are they people that you've blocked a few days ago (e.g. play a game and blocked that user a week ago, start a new game today, they manage to join)?
