### ISSUE TITLE
Valar Tokens after both Jaqen and s character left play

### ISSUE THREAD

**Issue by Martozar** [cryogen/throneteki#1550]
My opponent played Jaqen and put Valar tokens on my Cersei.  I returned her to my hand with Tower of the Hand and he got his Jaqen killed. I played Cersei again and she still had Valar token on her. 
I'm not sure if it would be possible to trigger it if an opponent could return his Jaqen from dead pile

**Comment by ystros** [comment]
Thanks! It looks like Jaqen leaving play tried to remove the already removed token, creating a phantom token that would display in the UI but not allow him to target the character if he made it back into play. Fix is on the way.
