### ISSUE TITLE
Randyll Tarly Limit 3 yet I only have 2? I want 3 but its making a stink.

### ISSUE THREAD

**Issue by DisturbedMikey1** [cryogen/throneteki#1562]
HOT SUMMER KNIGHTS -This is the decklist that is having problems. I am being told that it is invalid because Randyll tarly has a limit 3 yet I do not have 3 in the deck.

Faction:House Tyrell
Agenda: Kings of Summer
Draw deck:61 cards
Plot deck:7 cards
Validity:Invalid

Plot (7)
1x A Noble Cause
2x A Tourney for the King
1x Calling the Banners
1x Calm Over Westeros
1x Confiscation
1x Summer Harvest
Character (35)
3x Arbor Knight
1x Courtesan of the Rose
1x Garden Caretaker
3x Hedge Knight
3x House Florent Knight
3x Knight of Summer
1x Lady-in-Waiting
1x Maester Lomys
2x Margaery Tyrell (Core)
2x Ser Colen of Greenpools
2x Ser Hobber Redwyne
2x Ser Horas Redwyne
2x Ser Robar Royce
2x The Knight of Flowers (Core)
2x The Queen of Thorns (Core)
2x Randyll Tarly
Attachment (10)
2x Heartsbane
3x Knighted
3x Mare in Heat
1x Milk of the Poppy
1x Seal of the Hand
Event (7)
2x Growing Strong
2x There Is My Claim
3x Lady Sansa's Rose
Location (9)
1x Bitterbridge Encampment
3x Rose Garden
2x The Arbor
2x The Kingsroad
1x Renly's Pavilion

**Comment by ystros** [comment]
Odd. When I paste this deck in, there are only 58 cards, not 61 as it says from your summary. So it's marked as invalid for not enough draw deck cards. If I bring Randyll up to 3x and add another card to get it up to 60, it's marked as valid for me.

Did you copy / paste this deck from a ThronesDB deck or did you build it manually in the deckbuilder?

Out of curiousity, what browser and version are your using?

**Comment by zacchiro** [comment]
Closing, as the deck is indeed invalid for not having enough draw cards (the character card count in the decklist is off by 3 cards, probably due to cut/paste issue).
Please reopen if you'd like to report another related issue, e.g., imprecise error message.
