### ISSUE TITLE
Besieged vs. Beseiged

### ISSUE THREAD

**Issue by Martozar** [cryogen/throneteki#1579]
Seems like there is typo in "Besieged" plot: when creating a deck, Beseiged instead of Besieged works like valid name.

**Comment by zacchiro** [comment]
This is in fact a bug in the data backing thronesdb, which I've fixed just today: https://github.com/Alsciende/thronesdb-json-data/pull/205
It will be fixed automatically on Throneteki at the next deployment. (Keeping this bug report open as a reminder until then.)

**Comment by zacchiro** [comment]
done a minute ago by @cryogen
