### ISSUE TITLE
Cannot play Risen from the Sea from discard pile on Annals of Castle black turn

### ISSUE THREAD

**Issue by Martozar** [cryogen/throneteki#1591]
It should work, I think. Maybe the error was caused because I tried to play Risen on "No attachment" character before Annals turn and Risen was placed on top of my dicard and remained there even after more cards were discarded. I think game thinks it was attached and is not in discard or something like that.

**Comment by ystros** [comment]
I believe #1674 fixes this, since Risen wasn't being properly placed in the discard pile after being played on a 'No Attachment' character.
