### ISSUE TITLE
Valar token not cleared when character jump back to hand

### ISSUE THREAD

**Issue by zacchiro** [cryogen/throneteki#1595]
I had a Rhaegal in play with a Valar Morghulis token (by Jaqen) on him. I jumped him back in hand using The Iron Bank Will Have Its Due. Next turn I've played Rhaegal again (Jaqen was gone by then) and he entered play with the Valar Morghulis token still on him. Moving Rhaegal in and out the discard pile cleared the token.

**Comment by ystros** [comment]
Pretty sure this is a dupe of #1550, which was already fixed by #1566, which hasn't been deployed yet.

**Comment by zacchiro** [comment]
Ah, that explains it, thanks.
I was aware of that issue, but I thought it had already been deployed (and so not completely fixed).
Closing this as duplicate then.
