### ISSUE TITLE
Cant see duplicates

### ISSUE THREAD

**Issue by gewin1988** [cryogen/throneteki#1601]
A few days(or weeks) ago the site started to not show the duplicate signs on characters. Its very frustrating.
No green "D" icon on characters, if it should be killed, it is saved and in the chat log the usual "use duplicate to save" message could be read.

**Comment by zacchiro** [comment]
I can generally see duplicates, but it did happen to me once that a duplicate was invisible: it was with a duped Doreah who also had a duped attachment on her. The attachment dupe was visible, but the character one wasn't. And I'm sure in the past both were visible and distinguishable one from the other.
