### ISSUE TITLE
Beseiged still applying on next turn (after both players reveal it)

### ISSUE THREAD

**Issue by colonialbob** [cryogen/throneteki#1602]
Just played a game where both players flipped Beseiged round 1. Then on round 2, it still displayed the minimum 1 defender and 'x did not declare defenders' warnings, even though neither player had Beseiged as their revealed plot. I have played several games with Beseiged so far, flipping it round 1 multiple times, and this is the first time I've encountered that error. I think it must have to do with the double Beseiged.

**Comment by ystros** [comment]
Yup, definitely a problem w/ double Besieged. Thanks for reporting!
