### ISSUE TITLE
Running locally

### ISSUE THREAD

**Issue by ronderksen** [cryogen/throneteki#1616]
I've been trying to get the application to run locally, to better understand the inner workings of the app. I've managed to get so far that the page loads and I can make decks. However, it seems that the data isn't fully up-to-date. For instance, in your code you use `card.label` to get the card title, but in the data `card.name` is used. Do you use a data migration script to update the data after initial import, or am I doing it wrong?

**Comment by ronderksen** [comment]
Of course, just after this, I find the server/scripts directory. Running `node fetchdata.js` seems to be the trick. Might be a good idea to add that to the readme.

**Comment by zacchiro** [comment]
@ronderksen it is in the README :), section [Development](https://github.com/cryogen/throneteki/blob/master/README.md#development), 8th line of the first recipe to follow to run things locally.

Closing this.

**Comment by ronderksen** [comment]
Totally missed that, sorry.
