### ISSUE TITLE
saving/adding decks require acting twice and might result in duplicate decks

### ISSUE THREAD

**Issue by zacchiro** [cryogen/throneteki#1627]
[ known bug already, reporting here for tracking ]

The first click on the save or add deck buttons is delivered to the backend but does not result in closing the deck editor. The second click on the same button closes the deck editor.

This is annoying from a UI perspective, and also results in duplicate decks in the "add deck" case.

**Comment by cryogen** [comment]
Fixed in b6fa3db93632c768d2399b7d5e2db3f1455c685f

Never assume bugs are known, I knew nothing about this one :)

The deck editor was in a terrible state.. hopefully now it's less so
