### ISSUE TITLE
Nagga's ribs won't move duplicates, and other issues with the card

### ISSUE THREAD

**Issue by Duckbringer** [cryogen/throneteki#1639]
Nagga's ribs doesnt ask whether or not to move duplicate card to dead pile.

**Comment by Duckbringer** [comment]
also, concerning Nagga's ribs, once a character is out of discard pile it should not be affected by effects such as Now my watch begins. But ironthrone still allows it.

**Comment by ystros** [comment]
Thanks for reporting! This is more or less a duplicate of #1610 and #1623, but I'm inclined to leave it open for better visibility.
