### ISSUE TITLE
Your King Commands It should block power gain abilities from triggering

### ISSUE THREAD

**Issue by ploog** [cryogen/throneteki#1661]
I usually try to provide parameters when reporting issues but here I can't figure out what went wrong.  I had My King Commands Its as my plot.  Opponent was able to successfully use Mace Tyrell to gain power.  I believe it was during the marshaling phase but possibly it was between phases.

Also Cyrogen, if you see this.  Thanks for adding the league link!

**Comment by ystros** [comment]
Looking into this, it looks like the player is prompted for Mace Tyrell and can trigger it, but power isn't actually gained (though the chat message says it is). This affects pretty much every ability that has a character gain power, not just Mace.

Somewhat related: #1474
