### ISSUE TITLE
 Stormcrows do not modify STR of a character with already modified STR

### ISSUE THREAD

**Issue by Martozar** [cryogen/throneteki#1662]
I didnt test it on character with no STR modificators, but there was a situation, when my Jorah had -3 STR due to Consuming Flames and an opponent used Stormcrows ability to give him -1 STR and his STR was not changed. Had this situation several times with different negative STR modificators.

**Comment by DukeTax** [comment]
Thanks for reporting. :) This has been fixed already and will go live with the next deployment.
