### ISSUE TITLE
Nothing Burns should not allow to choose a location protected by Red Door

### ISSUE THREAD

**Issue by zacchiro** [cryogen/throneteki#1664]
Currently the location selection of Nothing Burns Like The Cold allow to pick a location protected by The House With The Red Door, which isn't a valid target thanks to its immunity from discard.

**Comment by DukeTax** [comment]
#1660 should have fixed this for any location discard effect (that didn't already have the gameAction property), but is not deployed yet.

**Comment by zacchiro** [comment]
Thanks for the pointer! I've just tested it on the development version with the specific plot, and I can confirm it does fix the issue. Awesome! :-)
