### ISSUE TITLE
Consolidation of Power

### ISSUE THREAD

**Issue by colonialbob** [cryogen/throneteki#1669]
Consolidation of Power allows the selection of a character from either player, when it is supposed to only be characters controlled by one player.

**Comment by colonialbob** [comment]
(To be clear it allows the player to select one character controlled by them *and* one character controlled by their opponent, when it should only allow them to select one or more characters controlled by themselves *or* one or more characters controlled by an opponent)

**Comment by ystros** [comment]
To anyone who tries to fix this one, the possible approaches seem to be:

1. Once a player has clicked on one character, choices are reduced to just other characters with the same controller. While this is the ideal solution, it may be difficult / impossible without significant changes to the targeting API.
2. Prompt the player to choose a player upfront, then only allow characters from that player. Introduces an extra click and is kind of awkward.
3. Keep things as they are UI wise but don't do the kneel or power move if characters from multiple controllers have been selected. Essentially, cancel the ability.
