### ISSUE TITLE
Bug: Theon Greyjoy Stealth

### ISSUE THREAD

**Issue by XMaratX** [cryogen/throneteki#168]
Just had a game in which Theon Greyjoy's Stealth trigger locked up the game. The opponent had no Military icon characters, but the game refused to let me move on by pressing "Done." Also, oddly enough, it let me start to kneel his cards instead of selecting them.

**Comment by cryogen** [comment]
I can't reproduce this, however I have fixed the kneeling of opponents cards.  Please provide a bit more info if you are able to reproduce this again

**Comment by doomnote** [comment]
May be related but it appears you can't skip applying stealth (it is optional). In XMaratX's case, he could have chosen someone even though they didn't have a military icon, but I just had a situation where opponent and I each had only 1 character, both with stealth, so we couldn't choose a target and were unable to click done to clear the prompt.

**Comment by cryogen** [comment]
That's the case I can't reproduce.  I can always click done and have it skip the step.  Need more information on what leads up to not being able to click done

**Comment by cryogen** [comment]
I think I've fixed this now.  I think what was happening is that every time you clicked on a card that wasn't a valid target, it added a new selection into a 'queue' so you had to hit done as many times as were in that queue for it to continue.  Please reopen if you can reproduce this still (After tomorrow as the change isnt live yet)
