### ISSUE TITLE
no log in

### ISSUE THREAD

**Issue by giuliobettelli** [cryogen/throneteki#1684]
i can't log in to the server... the message says: " An error occured communicating with the server. Please try again later." for 2 days.

**Comment by cryogen** [comment]
I think this was a temporary blip when I deployed the new account activation requirements.  Are you still getting this? If so can you clear your cache (www.clearyourcache.com) and try again?  If still getting the issue please let me have your username

**Comment by cryogen** [comment]
Closing this for now, please reopen if still experiencing issues
