### ISSUE TITLE
Brightwater Knight str not correct

### ISSUE THREAD

**Issue by DaceBonearm** [cryogen/throneteki#1688]
In my last game, I noticed when attacking or defending with Brightwater Knight the chat box would say I challenged with 0 str. My opponent and I checked repeatedly to see what could cause this. We couldn't find anything. Is this a bug? I also noticed Brightwater Knight wasn't given +3 str when I knelt Horn Hill (3 gold). Thanks.

**Comment by ystros** [comment]
There was a problem w/ the data for the card. The latest data has been fetched, so this should be resolved now.
