### ISSUE TITLE
(Chrome) Images in the second column of plot menu are not rendered properly

### ISSUE THREAD

**Issue by Grugn0** [cryogen/throneteki#1703]
As the subject... Images in the second column of plot menu are not rendered properly (on Chrome).
I've searched around and seems that depends on a sort bugs regarding columns css property, overflow hidden, absolute position, transformations (border radius) etc... (the link below)
The bug fix has no ETA and is old, so maybe it's better to think to some workaround.

just for example unsetting border-radius property on div with class "card-type-plot" :
```
.card-type-plot {
 border-radius:unset !important;
}
```

Here the link of the bug: https://bugs.chromium.org/p/chromium/issues/detail?id=527709

**Comment by cryogen** [comment]
Would it be possible to include a screenshot of the bug in effect?  Thanks!

**Comment by Grugn0** [comment]
Sure! 
![image](https://user-images.githubusercontent.com/8015654/35158215-bb8a0eac-fd36-11e7-8769-b6860162c2fc.png)

But you can always see the bug in KotBW Stream (https://www.youtube.com/watch?v=OUQE4GbiSCI&t=22s):
![image](https://user-images.githubusercontent.com/8015654/35158410-411f71d8-fd37-11e7-8373-66b5e5b61800.png)

At first I thought it was just my problem, but when I saw it in streaming....

**Comment by Grugn0** [comment]
Chrome Version 63.0.3239.132 (Official build) (64 bit) (Desktop)

**Comment by cryogen** [comment]
I think this has gone away now since we no longer use columns to layout the cards, but please confirm?

**Comment by Grugn0** [comment]
I can confirm, and my screenshot too 
![image](https://user-images.githubusercontent.com/8015654/38501909-591f491e-3c0e-11e8-8c9d-3080bbf584c3.png)

**Comment by cryogen** [comment]
Thanks!
