### ISSUE TITLE
Bug: Ward and Valar making cards inaccessible

### ISSUE THREAD

**Issue by Vicaroth** [cryogen/throneteki#171]
Had a few issues which Ward was on a character and after Valar, ward is removed and moves to the card owner's playing field. However, after this happens the card is inaccessible for either player. Neither player can kneel, move or remove card from play.

**Comment by DukeTax** [comment]
Had something similar. Warded a Cersei, which I then decided to sacrifice with Jon Snow's ability by dragging her to *my* discard pile (I tried dragging it to my opponents discard pile, wouldn't work). The card was then moved to my opponents play area where it was inaccessible (but did contribute STR to dominance).
