### ISSUE TITLE
Cannot leave "finished" games

### ISSUE THREAD

**Issue by jbrz** [cryogen/throneteki#1710]
Pretty big show-stopper here - pressing the "leave" button after a player has won or conceded results in... nothing.  No network calls, no console bugs/errors, no returning to the games lobby, no return to the main page.

It just sits there in the game.  Clearly hanging up on something.

@cryogen @ystros

**Comment by cryogen** [comment]
Fixed in 6a46a7aa28da6861268870d527568935141c1312

#oops
