### ISSUE TITLE
Non-terminal attachments

### ISSUE THREAD

**Issue by ploog** [cryogen/throneteki#1719]
I'm not exactly sure what the issue is but a bodyguard originally placed on a friendly character that was stolen (ward) failed to return to hand when the character was killed.  I was unable to test to see the extent of the problem.  It could be all attachments or just attachments on opposing characters or just attachments on characters that you don't control or even just specifically related to an unused Bodyguard.  I apologize for the vagueness

**Comment by ystros** [comment]
Thanks for the report! It was a problem with all non-terminal attachments, not just on opponent cards. #1721 will fix the problem.
