### ISSUE TITLE
3 Issues

### ISSUE THREAD

**Issue by thanivar** [cryogen/throneteki#1723]
1.- Att don't go to hand (after reading here i think this was/is already addressed)
2.- Turn after "a song of summer" the str buff keeps being on the char (resolved it with the /str x command)
3.- Can't play or put into play character in the other player dead pile.

Cheers

**Comment by ystros** [comment]
Thanks for the report! #1721 will fix the attachment issue and #1725 should fix the Song of Summer (and other plot) issue.

Could you expand on the scenario you encountered for not being able to put into play characters when that character is also in the opponent's dead pile? Was take control involved?

**Comment by thanivar** [comment]
NO take control. My opp triggered bitterbridge encampment and his renly was dead. I wanted to put my renly into play with it and didn't let me ....the bug may be something with bitterbridge.

Cheers!

**Comment by ystros** [comment]
The Bitterbridge problem is fixed with #1747 and should go out in the next deploy. Thanks!
