### ISSUE TITLE
A Bunch of Problems

### ISSUE THREAD

**Issue by PulseGlazer7** [cryogen/throneteki#1724]
1. After plot Retaliation is used, that player is forced to go second whenever he or she wins initiative.
2. Balon Greyjoy, Ser Jaime Lannister, and Wolf King do not stand when initiating military challenges.
3. Attachments, when they are not terminal, are discarded when a character leaves play.

Thank you!

**Comment by ystros** [comment]
Thanks for the report! #1725 should fix the issue with Retaliation (and other plots), #1720 should fix the inappropriate kneeling for "does not kneel" characters, and #1721 will fix non-terminal attachments.
