### ISSUE TITLE
Fear Cuts Deeper Than Swords

### ISSUE THREAD

**Issue by aPPLE-dAY** [cryogen/throneteki#1728]
Hi there,

I am having an issue with the triggering of Fear Cuts Deeper Than Swords - I am not being prompted when criteria to play it have been met (eg. when Quentin Martell triggers and chooses a Stark character).  

Didn't see a listing for it, or if there was a setting that needed to be activated.  Thanks.

**Comment by DukeTax** [comment]
Thanks for reporting. Fear Cuts Deeper Than Swords is entirely unimplemented at the moment. The listings for unimplemented and partially implemented cards can be found here: https://github.com/cryogen/throneteki/projects
