### ISSUE TITLE
Chat's disappearing trick.

### ISSUE THREAD

**Issue by jbrz** [cryogen/throneteki#1743]
**_[See bottom of this post for 'solution' ]_**

Perhaps just a canary issue? I'm not sure yet / haven't had enough games to test that, but I guess to be sure I still need some confirmation of what exactly I'm looking at...

So there seems to be _something_ that triggers chat disappearing on me in-game.  It might just be hitting the bottom of the initial chat windowspace, but again, I'll need to test further to be sure (I don't think that's it):
<img width="377" alt="screen shot 2018-02-14 at 10 18 41 am" src="https://user-images.githubusercontent.com/14303017/36212500-1739c360-1172-11e8-8ef4-674c26601925.png">

Console shows the following errors, and I'm wondering if that's part of the issue.  Unfortunately I wasn't smart enough to have the network tab up before these appeared, so I guess that's where I would want to ask you guys what could possibly be trying to load that would hit a 404 and/or cause this chat nonsense (challenge icons?)
<img width="599" alt="screen shot 2018-02-14 at 10 23 39 am" src="https://user-images.githubusercontent.com/14303017/36212501-17491b8a-1172-11e8-830b-6fad754c1de1.png">

I will update further after I've investigated some more, but I figured I would start here at least.

Hilarious update: ok I think I can confirm that it's a canary build issue with expanding written text areas.  I literally went to update this post, hit enter at the bottom of the post a couple of times, and all the sudden my text is cut off.  I'm literally blind typing this as we speak. So I guess you guys can ignore me? :P I would still be interested to know why there's an undefined png being 404'd though...

**Comment by cryogen** [comment]
Cute.  I've raised the 404 as #1744.  Thanks for reporting!
