### ISSUE TITLE
Bitterbridge restricts playable cards based on Bitterbridge owner's game state

### ISSUE THREAD

**Issue by illurion** [cryogen/throneteki#1746]
When player 1 kneels bitterbridge, the site only allows player 2 to play cards from their hand that would be legal for player 1 to play. For instance, if both players are tyrell and Renly is in player 1's dead pile, the game will have Renly grayed out in player 2's hand and won't allow him to be selected by player 2. Instead, the site needs to check each player's legal targets based on their own board state, instead of using player 1's for both.

**Comment by DukeTax** [comment]
Thanks for reporting and narrowing it down correctly.
