### ISSUE TITLE
Chat typing bug

### ISSUE THREAD

**Issue by jbrz** [cryogen/throneteki#1749]
When typing a message in chat, if you try to go back anywhere in the message you're typing and edit/add something, your cursor will immediately jump to the end of the message after the first character entered.

Repro'd on Chrome, Firefox, Safari.

My guesses: it has something to do with either the `typeahead` (or maybe just the autofocus attr?) or it's a react issue with onChange firing with every character and for some reason resetting your cursor to last position (which would be a bigger pain and seems less likely)

**Comment by cryogen** [comment]
This is actually a bug in a dependant component that we use: react-bootstrap-typeahead.  I thought that updating to the latest version made this issue go away but it seems not :(

It could be that the latest version isn't in the bundle, I'll double check that

**Comment by cryogen** [comment]
Yup, I was right, the wrong bundle was deployed.  Should be fixed now
