### ISSUE TITLE
Invalid username or password. Please check and try again

### ISSUE THREAD

**Issue by rimmok** [cryogen/throneteki#1771]
Hello. Everyday when from 2 ago, when i try to log in i only can read "Invalid username or password. Please check and try again". This happens to me and other two guys whitch share a float, i don't know if it was a bug. Sorry for my english.

**Comment by cryogen** [comment]
Nice try Mr Viper.  Your accounts (all of them) are staying banned.

In the highly unlikely event that you are actually not The Red Viper then I suggest you have a talk with your flat mates about why your account is inaccessible.
