### ISSUE TITLE
Venomous Blade can be marshalled  even if you are not the active player.

### ISSUE THREAD

**Issue by Grugn0** [cryogen/throneteki#1786]
A player with enough gold during marshalling, can "marshal" a Venomous Blade while he is not the active player.
Each player can take actions during marshalling but ony the active player can take marshal actions and marshal cards.

Other type of cards does not have this issue.

maybe it's a bug due to the fact that the card has the "ambush" keyword.

Reading the code it did not seem to me that this rule was strengthened on the server side.
Maybe the restriction is only implemented client side and the "ambush" keyword function as a backdoor in marshalling.
![image](https://user-images.githubusercontent.com/8015654/36839179-8ebc3f64-1d41-11e8-94ff-3b235ebcecb6.png)

> Topolino is the active player, but Paperino (with enough gold) can marshal his venomous blade.

I also tried with dornish spy: same issue.

**Comment by zacchiro** [comment]
This is actually by design, a player can marshal also during the opponent player marshaling phase, as that makes it easier to correct for mistakes. It's not specific to the cards you mention at all. It might be worth to document it better, though.

**Comment by cryogen** [comment]
It's not by design, in as much as it'll cause more problems to fix it than not :)

**Comment by Grugn0** [comment]
You're right (my mistake), I tried with a roseroad and it did not allow it (but this maybe due to a problem with the limited keyword that I reported), so I've wrongly supposed to be the ambush keyword .
Anyway it would be better that it was reported as a warning in the chat (but in this case it is an improvement and not a problem).
