### ISSUE TITLE
Balon Greyjoy (CtA) abbility can be used before challenge is initiated  

### ISSUE THREAD

**Issue by Martozar** [cryogen/throneteki#1819]
BG (CtA) can give +1 STR all loyal characters till the end of the challange, but now he can be used even when  no challenge is declared. Regardless of it is not a challenge action it cannot be used outside of challenge.

If he boosts character outside of challenge, characters have +1 STR until the next challenge is finished. I just tried to use his abbility in plot phase and characters were boosted all the phases until I done one of my challanges. And before challenge was resolved I cannot use his abbility again
![screenshot from 2018-03-11 11-56-42](https://user-images.githubusercontent.com/12549253/37252569-508af3e0-2523-11e8-88fa-571b681a285b.png)

**Comment by DukeTax** [comment]
Good catch, fix is PR'ed.
