### ISSUE TITLE
Deck builder caches unsaved changes

### ISSUE THREAD

**Issue by ystros** [cryogen/throneteki#1825]
### Scenario:
* Edit an existing deck
* Add some cards to the deck or delete some existing ones
* Without clicking Save, navigate to the Decks page

### Currently:
* When viewing the deck, whatever cards were in the deck after editing it are listed

### Expected:
* When viewing the deck, it should have the same cards it had before editing it.

**Comment by jbrz** [comment]
is this just a result of the `this.props.updateDeck(deck);` being included...virtually everywhere in the deckbuilder?  It's actually saving the 'copy' created by a change in the cards as the deck, or am I being daft?

**Comment by cryogen** [comment]
Yeah, something like that.  Once upon a time it had some code to revert those changes.  Not entirely sure what happened to it.  The deck builder is... not my best work!

**Comment by jbrz** [comment]
What's up with the thronesdb API?  I can't say I've meddled around with it at all, but I'm expecting to have a little more time relatively soon, could certainly look at both that and this in concert.  I didn't see any issues in the tdb repo that stood out...

**Comment by cryogen** [comment]
The oauth api throws a http 500 when you try to use it, with no indication as to why
