### ISSUE TITLE
Cersei (LoCR) triggers for each card discarded

### ISSUE THREAD

**Issue by doomnote** [cryogen/throneteki#184]
Cersei should only trigger once when discard happens, not per card. So if claim 2 or playing Without His Beard for example, it's prompting to trigger for each card discarded.

**Comment by cryogen** [comment]
This is more complicated to fix.  In the meantime, declining the second trigger (or reminding your opponent to do so) is a workaround

**Comment by ystros** [comment]
LoCR Cersei actually no longer prompts at all when a card is discarded. So it's broken in the other direction now.
