### ISSUE TITLE
unable to fetch some cards using fetchdata.js script

### ISSUE THREAD

**Issue by hrnciar** [cryogen/throneteki#1853]
Hello,

I am trying to clone throneteki and maybe try to help with some cards. I am having an issue with fetchdata.js script. Some cards are not available to be downloaded and at the end script ends with this error. Am I doing something wrong or it's error on ffg that some cards are unavailable? 

Thank you.

Tom 

```
Downloading image for 02120
Unable to fetch image for 11011 from http://lcg-cdn.fantasyflightgames.com/got2nd/GT31_11.jpg
Unable to fetch image for 11016 from http://lcg-cdn.fantasyflightgames.com/got2nd/GT31_16.jpg
Unable to fetch image for 11017 from http://lcg-cdn.fantasyflightgames.com/got2nd/GT31_17.jpg
...
Downloading image for 02020
/Users/Tom/Documents/Programovanie/throneteki/server/scripts/fetchdata/CardgameDbImageSource.js:23
        let cgdbId = pack.cgdbId.toString().padStart(2, '0');
                                 ^

TypeError: Cannot read property 'toString' of null
    at CardgameDbImageSource.fetchImage (/Users/Tom/Documents/Programovanie/throneteki/server/scripts/fetchdata/CardgameDbImageSource.js:23:34)
    at Timeout.setTimeout [as _onTimeout] (/Users/Tom/Documents/Programovanie/throneteki/server/scripts/fetchdata/CardImport.js:48:38)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
```

**Comment by cryogen** [comment]
Images that are not found are probably spoiled cards that are not on the ffg website yet

The error shouldn't really be happening but isn't anything to worry about :)

If the rest of the images have worked then I'd say you're good to go

**Comment by ystros** [comment]
Thanks for the report! The crash was happening when trying to fetch images for the Valyrian Draft pack (VDS), so any pack codes after that (including WotN and WotW) would likely not fetch images properly.

#1855 should fix it!
