### ISSUE TITLE
At Prince Doran's Behest and multiple "When Revealed" triggers

### ISSUE THREAD

**Issue by powerguynz** [cryogen/throneteki#1864]
So this seems to be an issue specific to this plot at the moment (but is technically a timing issue for plots in general). Basically if player A reveals At Prince Doran's Behest and player B reveals any other plot with a "when revealed", and then player A chooses another plot with a "when revealed" (from At Prince Doran's Behest) then the first player should have the control over the order the remaining plots trigger.

Example:
Player A flips At Prince Doran's Behest, Player B flips Marched to the Wall.
Player B chooses to be first player and chooses to resolve At Prince Doran's Behest first.
Player A reveals Valar Morghulis.

With the current implementation the first player chooses which player resolves their "when reveals" first, rather than choosing which plots trigger first. So Player A resolves all of their plot effects at once, so will immediately trigger the Valar. However I believe what should happen is the first player should be able to trigger Marched to the Wall prior to the Valar if they choose to.

The exact same thing will happen if both players flip At Prince Doran's Behest, just with an extra iteration.

Relevant ruling.
http://www.cardgamedb.com/forums/index.php?/topic/38115-at-prince-dorans-behest-questions/

**Comment by DukeTax** [comment]
Thanks for reporting, and you're completely right. It was implemented like this at first to get an implementation ready for release. But doing it right requires more game engine changes.

**Comment by Furyrex** [comment]
Regarding this plot, there is a funny interaction (Behest-Riddle as reported by the user Wordsmith in the same post [http://www.cardgamedb.com/forums/index.php?/topic/38115-at-prince-dorans-behest-questions/](url)) which it's not working currently. 

Example (2 Martell players):
Player A reveals Behest, Player B reveals Riddle and wins initiative.
Player B chooses to resolve Riddle and reveals his own Behest.
Now Player B could reveal a third plot card but in game you can't do this and you're stuck with your second Behest.

I hope I got this right without opening a new discussion.
