### ISSUE TITLE
Hotah's Axe - triggering twice when duped

### ISSUE THREAD

**Issue by drnovak77** [cryogen/throneteki#1877]
Hotah's Axe is unique and therefore a duplicate when 2x is attached to a character.

Attached character gets +6 in strength as the duplicate falsely triggeres the +3 strengt twice.

**Comment by cryogen** [comment]
Unfortunately it's not quite that simple, as I can't reproduce that simple case.  Is there anything else you can add about the board state that might have had an impact?

**Comment by drnovak77** [comment]
Sorry, I was just watching a game, popped in halfthrough and noticed that Nymeria had +10 strength with 2 x Axes attached, asked the players and they hadn't noticed. Perhaps the Martell player did something manually when marshalling/ambushing the attachement that caused it. I did notice that both Axes faceside up though, so that it seemed to be treated as to separate attachments. Hope it helps, will report with more details if I see it happen again :) Lovely work on your site btw, keep it up!

**Comment by cryogen** [comment]
I think @DukeTax has a reproduction now :)

And it is as you say, it seems to be getting attached twice, rather than being duped!

I'm sure a fix will be forthcoming
