### ISSUE TITLE
Chat Window Height

### ISSUE THREAD

**Issue by Simonmmm** [cryogen/throneteki#1888]
I'm using Windows 10, Firefox.

The height of the "table" ie. the distance between my cards & the opponents is being defined by the chat. Therefore I have to keep closing the chat window to see what going on.

Thanks!

**Comment by cryogen** [comment]
I don't think that's what's happening - I think you're suffering from having a small screen and the removal of the scrollbars from the game board.

Can you include a screenshot?

**Comment by Simonmmm** [comment]
No, it's on a 4k screen and the chat window was litterally the height of **all **the chat. Although it's stopped happening since the last "update", so it's all good.
If it happens again I'll include a screenshot.

**Comment by cryogen** [comment]
Ah yes, that was the original issue with FireFox that was fixed last night.  Thanks!
