### ISSUE TITLE
Opponent's Discard/Dead Window pops out of the Screen

### ISSUE THREAD

**Issue by Grugn0** [cryogen/throneteki#1893]
...is visible only a slice of the lower part of the window.

Browser Chrome 65.0.3325.181 (official build) (64 bit)
OS: WIndows 10

To take this screenshot I'm logged in as a spectator (I don't have tryed as a player):
![image](https://user-images.githubusercontent.com/8015654/38507984-453f7f1c-3c1e-11e8-82b4-bb56d19ef7c2.png)

**Comment by cryogen** [comment]
I deployed a fix for this earlier today, refresh and/or clear cache, let me know if it persists.

**Comment by Grugn0** [comment]
Clearing cache works. Sorry I should have thought about it before creating a new issue.

**Comment by cryogen** [comment]
Not a problem, I only fixed it this afternoon :)
