### ISSUE TITLE
Drowned Gods Blessing

### ISSUE THREAD

**Issue by TheTank89** [cryogen/throneteki#1903]
Hi there

My opponent used Like Warm Rain to kill a character of mine that had the Drowned Gods Blessing. This does not seem right.

**Comment by DukeTax** [comment]
Thanks for reporting. That part of Drowned God's Blessing is not implemented yet (we keep a list here: https://github.com/cryogen/throneteki/projects/1), so not a real bug but definitely something that should get implemented. :)

**Comment by TheTank89** [comment]
Ah fair! Should probably have looked there first. :)
