### ISSUE TITLE
Old Wyk and unique drowend god characters

### ISSUE THREAD

**Issue by Grugn0** [cryogen/throneteki#1913]
Scenario:
Old Wyk in play Tarle the Thrice-Drowned both in play and as the top card in the dead pile.
I declare a Power Challenge with another character without declaring Tarle as a partecipant.
If I use Old Wyk reaction, Tarle should only be duplicated, but instead he is also made a participant (but not kneeleing) and his strength added to the challenge.
If Tarle was already participating instead his strength is added a second time.

I used Tarle in this example but any other unique drowned god is fine..

**Comment by cryogen** [comment]
I can't reproduce this.

@DukeTax @ystros did this get fixed recently by something I'm not aware of?

**Comment by Grugn0** [comment]
I'm still able to reproduce (solo mode)...
After having built an appropriate game state, I declare a power challenge with only an "Iron Island Fishmonger"
![image](https://user-images.githubusercontent.com/8015654/38804802-f0f4664c-4173-11e8-9292-64cae38d3f42.png)
After activating Old Wyk reaction (Challenge Str would be 1)
![image](https://user-images.githubusercontent.com/8015654/38804889-3ea7217c-4174-11e8-994e-5463b62fe7ab.png)
After challenge result determination (Challenge result would be 1 vs 0 )
![image](https://user-images.githubusercontent.com/8015654/38805062-ca8aec6e-4174-11e8-94bf-5e03a839c669.png)



Here with only Tarle declared as attacker (Strength would be 4)
![image](https://user-images.githubusercontent.com/8015654/38805269-87eac590-4175-11e8-91b1-2fd7bd51998f.png)

**Comment by cryogen** [comment]
Sure, I don't doubt that you can, I'm just checking with the others whether this was fixed recently but isn't get deployed on the live server :)
