### ISSUE TITLE
When to play "Taste for Flesh"?

### ISSUE THREAD

**Issue by Burner4** [cryogen/throneteki#1951]
I'm new to the game, so this is possibly an understanding issue on my part, but when can I play "Taste for Flesh"? My reading of the card is I play it after winning a challenge, but no pop up happens here. Is it not implemented or am I just doing it wrong?

**Comment by DukeTax** [comment]
Taste for Flesh is a reaction to winning a challenge, so you will get prompted to play it upon winning a challenge if:

1. You had an attacking Direwolf.
2. There is a legal target to kill, in this case a defending character.

It is possible you've confused "defending character" with "character controller by the defending player", which are obviously not the same. If you are sure this was not the case, perhaps something else prevented you from triggering abilities, for example Catelyn Stark or Winterfell? I'll close this issue for now but you can keep posting here if you have any more questions and/or comments. :)
