### ISSUE TITLE
Problem with actions/reactions in marshalling

### ISSUE THREAD

**Issue by sergselin** [cryogen/throneteki#1966]
Hello, the following game situation occurred.

I have 1 gold on Begging Brother and 1 gold on The Great Sept of Baelor. During previous round I have put Milk of the Poppy on Robert. Now the opponent marshals maester Cressen. The reaction of The Great Sept of Baelor is triggered for me to decide, but the opponent did not wait and knelt Maester Cressen too fast and removed Milk and only then I could react to it with my Sept and begging brother.

![1](https://user-images.githubusercontent.com/39171688/39959910-ad8aef30-5621-11e8-8d2f-35221c5de5a9.PNG)

**Comment by sergselin** [comment]
Hello, it is ok with me if there will be at least warning, today the game freezes today the whole day during marshaling. Is it somehow connected to implementation? Thanks!

**Comment by DukeTax** [comment]
The proposed solution for this is not online yet, so this must be a separate issue.
