### ISSUE TITLE
maester Aemon tutored with Here To Serve plot doesn't get +1 STR from The Wall

### ISSUE THREAD

**Issue by zacchiro** [cryogen/throneteki#198]
All is in the title :)
Workaround is trivial, put Aemon back to your hand and then back in play; it gets the +1 then.

**Comment by DukeTax** [comment]
This is comparable with A Time for Wolves putting Summer in play while having Winterfell up. Typing /str 4 (or /str 3 in your example) and clicking the character is also a solution.
