### ISSUE TITLE
Iron Mines issues

### ISSUE THREAD

**Issue by doomnote** [cryogen/throneteki#202]
On a Valar turn, after selecting YES to save a character, iron mines is discarded and used to save but you are prompted if you want to use it for every other character as well. Once you click YES and use it, it should stop asking. 

Or perhaps when there is more than one option, turn it into a chooser prompt and click the character you want to save so it only has to ask 1 question.

**Comment by cryogen** [comment]
We currently have no way to stop events from propagating to other event handlers.  Until I rewrite this to be a possibility, this is going to be an annoyance during Valar.

**Comment by uBaHoB** [comment]
Also if you have 2x Iron mines, and they prompt for the same character. When you press no for the second Iron Mines prompt the character dies. Also characters with Dupes are not in the list for saves you may want to save them with mines and not dupes in mass resets.

**Comment by cryogen** [comment]
Same issue :)
