### ISSUE TITLE
Fear Cuts deeper than swords vs. Shadows

### ISSUE THREAD

**Issue by sergselin** [cryogen/throneteki#2036]
Hi,

Fear Cuts Deeper than Swords did not react to Shadow Priestess kneeling my character out of shadows.
Could you correct? Had to do manually.

Thanks,
Sergey
![default](https://user-images.githubusercontent.com/39171688/41439206-8e498dd6-7032-11e8-87fb-dc9467ba1a06.PNG)

**Comment by DukeTax** [comment]
Thanks for reporting. I haven't been able to reproduce this.

![schermafbeelding 2018-06-14 om 23 39 30](https://user-images.githubusercontent.com/23409205/41439815-73de3e98-702c-11e8-9703-9dea4725d104.png)

**Comment by sergselin** [comment]
yes you're right - my bad, sorry.
