### ISSUE TITLE
Blackfish kneeling

### ISSUE THREAD

**Issue by sergselin** [cryogen/throneteki#2037]
Hi,

I have a Blackfish with 4 power, but he still knelt when declared as an attacker. Could you correct?

Thanks!
![2](https://user-images.githubusercontent.com/39171688/41439274-d28f9e90-7032-11e8-9099-17ef6211da85.PNG)

**Comment by ystros** [comment]
Thanks for the report and the screenshot! I haven't been able to reproduce this so far. I put 4 power on Blackfish, initiated a challenge with him, and he continued to stand as expected. Have you seen this happen in games since then?

**Comment by ystros** [comment]
Thanks! That I'm able to reproduce. Will have to look into it more closely.
