### ISSUE TITLE
Add a Chat Message for Claim

### ISSUE THREAD

**Issue by doomnote** [cryogen/throneteki#204]
Following the chat makes it really easy to see what happened and that nothing was missed, but it doesn't seem there are any messages for claim, unless the claim is 0 and it let's you know.

Player A takes X Power from Player B for claim, for example.

Where it would really help is saving with a dupe on mil claim. Often if you're not watching closely it looks like nothing happened and claim was missed. 

Player A chooses to kill Character for claim, and discards a dupe on Character to save - or something like that would be helpful.

**Comment by cryogen** [comment]
I added a message for when a dupe is used in 21a7bef64f3fdf67d72adf2834887a79fe3153e6

I think the other messages are reasonable requests and will look at adding them
