### ISSUE TITLE
Saving The Hound from going back to your hand with a duplicate

### ISSUE THREAD

**Issue by DukeTax** [cryogen/throneteki#215]
If you win a challenge with a duped Hound, and you choose to not discard a card at random for his forced reaction, you should be able to save The Hound from going back to your hand by discarding his own dupe. At the moment he returns to your hand and the dupe is discarded as well.

**Comment by cryogen** [comment]
This is a perfect use for my shiny new method to return cards to hand while allowing a save!

**Comment by DukeTax** [comment]
It is? Cool! Or do I fail at detecting sarcasm here? :)

**Comment by cryogen** [comment]
No it is, i just implemented it this morning for the first snow of winter :)

**Comment by DukeTax** [comment]
Ok thats great! :P
