### ISSUE TITLE
The Haunted Forest still contributes strength after being knelt.

### ISSUE THREAD

**Issue by AisoRed** [cryogen/throneteki#228]
Steps to Reproduce:
1. Play an opponent using The Haunted Forest.
2. Initiate and win a challenge against this opponent.
3. Opponent is forced to kneel The Haunted Forest.
4. Subsequent challenges in which none of the opponent's characters are declared as a defender are not unopposed. The Haunted Forest is still contributing strength to the challenge.

**Comment by cryogen** [comment]
Fixed in bdb6f03d004140cc5c413992dcb081e06209c3ae just waiting for a deployment

**Comment by AisoRed** [comment]
Cheers! Thanks for the hard work on this.
