### ISSUE TITLE
Red Keep - Contributing STR

### ISSUE THREAD

**Issue by MariosRizlasWet** [cryogen/throneteki#230]
Had a slight issue with the Red Keep giving +2 to POW challenges, I found that when attacking with characters which denied STR (Balon specifically) the Red Keep would simply add +2 to any participating character, rather than the controlling player's side in general.

e.g.  I am attacking with Balon alone in a POW challenge, opponent defends with Melissandra - I should win by 5-2 (assuming no other modifiers) but the STR was decided at 5-6 (Mel + Red Keep).  I'm not certain if this issue is with Balon or The Red Keep tbh.

**Comment by cryogen** [comment]
This is just down to Balon not being implemented :)

**Comment by MariosRizlasWet** [comment]
OK cracking, wasn't certain where the issue was, should have guessed it was in my ability to check the implementation list ;)
