### ISSUE TITLE
UO power timing issue

### ISSUE THREAD

**Issue by DukeTax** [cryogen/throneteki#233]
At the moment UO power is awarded immediately upon winning a challenge unopposed, before reactions to the 'Determine Winner' step. Not a huge deal but consider a Lannister vs Martell with Lannister at 14 power winning an intrigue challenge unopposed with Tywin who has 3 power from renown. The Lannister here will win before Martell can trigger Ghaston Grey, which shouldn't happen.

**Comment by cryogen** [comment]
That is not the case. DUCK is obeyed. Can you provide a more concrete example?

**Comment by DukeTax** [comment]
I've been trying to reproduce reactions triggering after gaining UO in a solo game just now - and I couldn't. So you must be right. I think my confusion must have come from opponents 'manually triggering' certain reactions after gaining UO (so too late), which I must then have attributed to the system. My bad!
