### ISSUE TITLE
Kingsroad knelt by Lordsport Shipwright bug

### ISSUE THREAD

**Issue by DukeTax** [cryogen/throneteki#235]
Getting your Kingsroad knelt by an opponents Lordsport Shipwright activates it and reduces your next marshalled character, defeating the purpose of the Shipwright.

**Comment by cryogen** [comment]
Ha.  Cute.  I think @ystros and I have similar desires to change the way reducers work in general, which should fix this

**Comment by ystros** [comment]
@cryogen I think you fixed this one in 3c908e429560bca3a336aedb41143e8bfce72670, correct?

**Comment by cryogen** [comment]
Correct
