### ISSUE TITLE
Misleading Robert Baratheon STR messages when declared as defender/attacker

### ISSUE THREAD

**Issue by DukeTax** [cryogen/throneteki#236]
When Robert Baratheon is added to a challenge, the chat message declaring total attacking or defending STR uses Robert's STR as it was right before declaration I believe. Example: I do a power challenge with Robb and Catelyn for 9. Opponent defends with Robert and two dragonstone faithfuls (all other characters are standing). The game will declare total defending STR to be 9 even though it's 11. Challenge resolution goes through fine so it's not a huge deal, but it might be a little misleading when the challenge is 9v9 according to the chat, no further actions are taken, and suddenly you have lost 9v11.

**Comment by ystros** [comment]
Thanks for flagging this, I was vaguely aware it may be an issue but had kind of forgotten. This is a general bug in how strength boosts that rely on game state are calculated, so some other cards probably have the same problem. Currently the boost is calculated at the end of a 'game step' but they really need to be calculated as state changes.
