### ISSUE TITLE
Deck builder should validate Fealty agenda rules

### ISSUE THREAD

**Issue by ystros** [cryogen/throneteki#238]
The deck builder does not mark decks using the Fealty agenda that contains more than 15 neutral cards as invalid.

**Comment by doomnote** [comment]
Does the Deck Builder invalidate any agenda violations? And can you still load and play invalid decks? That's probably a bigger issue

**Comment by cryogen** [comment]
You can play invalid decks.  Eventually it will show if your opponent is using an illegal deck or is using unreleased cards in the pending game lobby.

Other agendas are implemented, I just missed fealty cause i didn't read the card!
