### ISSUE TITLE
allow to manually trigger Rains of Castamere

### ISSUE THREAD

**Issue by zacchiro** [cryogen/throneteki#252]
Rains of Castamere currently works, but cannot be triggered manually.
In some cases that is annoying, as there is no way to recover from bugs and/or errors. For instance, the fact some cards are not implemented yet might make the difference between winning an INT challenge by 5 or more. But once the challenge is over, there is no way to trigger Rains.

Please allow Rains to be triggered by hand.
In terms of UI, the choice seems straightforward: pop up menu on the Rains agenda card.

Thanks for considering!

**Comment by cryogen** [comment]
Fixed in 1077fd2b0f2941d6c35f92af7e887e8d1c05066d
