### ISSUE TITLE
allow to browse the list of (remaining) Scheme plots for Rains of Castamere

### ISSUE THREAD

**Issue by zacchiro** [cryogen/throneteki#253]
There seems to be no way to browse through the 5 (or less, depending if you've already triggrered rains or not) scheme plots that the plot deck includes when the agenda card is Rains of Castamere. Can we haz it?

Thanks for considering!

**Comment by ystros** [comment]
As an update, I have a branch that adds the backend to do this (as well as view cards that have been removed from the game - the played Schemes, Varys after using his ability, etc). I've been waiting for a proposed UI change to go through before I continue on it and expose it.

**Comment by zacchiro** [comment]
Just my 0.02 EUR:
- for removed-from-game cards: an additional pile to the right of the dead pile seems the way to go. Bonus point is the pile is completely invisible when no card has been removed from the game, given that does not happen very often (at least in the current meat)
- for castamere schemes that haven't been played yet, i'd mimic what people do in reality: just keep the schemes together with the other plots. Bonus points: show them with a different border, and have separate counters shown on the plot deck if Rains is being used, e.g., Plots (6), Schemes (3). Yes, i understand all this will be fairly ad-hoc coding just for Rains :-(
