### ISSUE TITLE
/show x

### ISSUE THREAD

**Issue by TheJunik** [cryogen/throneteki#26]
Feature: implement command /show x (x is the number of first x cards from the top of the deck)
Reason: many cards allow you to look at or search first x cards of your deck, for example:
        Greenblood Trader: /show 2
        Summons: /show 10
        Upcoming Pyat Pree: /show x (x is variable based on challenge result)

**Comment by cryogen** [comment]
I'd rather implement the cards that have this effect than have a command for it, for now you can work around it easily enough with show deck/shuffle
