### ISSUE TITLE
Summer Harvest granting too much gold

### ISSUE THREAD

**Issue by DukeTax** [cryogen/throneteki#261]
Just had a Summer Harvest vs A Noble Cause with 2 roseroads out grant me 16 gold in marshalling. No idea what could have caused it; we were in the second plot stack already though.

**Comment by ystros** [comment]
So far I haven't been able to reproduce this by explicitly playing Summer Harvest vs Noble Cause. Do you remember if you got too much gold in later rounds as well (possibly indicating a problem with Roseroad)?

Let us know if you see it again / other income weirdness.

**Comment by DukeTax** [comment]
Later rounds gave correct amounts of gold. I'll keep an eye out although I don't play Summer Harvest much.

**Comment by DukeTax** [comment]
Had this again. Got 11 gold against a First Snow of Winter. We were in the second plot stack again.

**Comment by cryogen** [comment]
Happened to me too - also second time around in plots

![image](https://cloud.githubusercontent.com/assets/1053365/23040490/6510d3dc-f489-11e6-87bc-d99c753ea0d6.png)
