### ISSUE TITLE
Allow manual resolution of When revealed abilities of plots (no auto resolution)

### ISSUE THREAD

**Issue by TheJunik** [cryogen/throneteki#27]
Feature: Stop resolving When revealed abilities of plots automatically when plots are chosen.

Reason: It is up to the first player who determines in what order plots are triggered. There are many situations when the order of When revealed abilities makes a difference.

Note: It is much easier to allow players handle different abilities manually, e.g. draw, kill, basically moving cards around. Implementing each plot ability automatically is time consuming, error prone and inflexible.

**Comment by cryogen** [comment]
FYI, This is being worked on at the moment

**Comment by samuellinde** [comment]
I don't think it's an either/or scenario. I agree that getting things to work manually first and foremost is a priority but having card effects resolve automatically as much as possible would make for a great play experience as well.

**Comment by TheJunik** [comment]
that was my intention. first make it happen manually so that the game rules can be applied. later automatic resolution.

**Comment by cryogen** [comment]
When revealed is now up to the first player
