### ISSUE TITLE
Allow for actions windows

### ISSUE THREAD

**Issue by TheJunik** [cryogen/throneteki#28]
Reason: there are multiple action windows that allow players to trigger various effects which can alter game elements in subsequent phases/steps.

action windows:
1. plot phase, after plots are revealed
2. draw phase, after cards are drawn
3. marshalling phase, after collecting income
4. challenges phase
  4.1. pre-challenge
  4.2. after challenge is initiated
  4.3. after defenders are declared and before challenge is resolved
5. dominance phase, after dominance is resolved
6. standing phase, after cards stand
7. taxation phase, after discarding for reserve

Circumvention: many of them can be applied prior to taking actions in subsequent phases, but some of them come too late.
1. skipped. Can be done only after drawing cards during marshalling.
2. can be done before starting to marshall cards (but still after collecting income)
3. ok,
4.1. ok
4.2. ok
4.3. skipped. can be done post automatic challenge resolution only. Probably the most important one.
5, 6, 7. not sure right now. If I remember correctly all of these can be done only at the end of round.

**Comment by ystros** [comment]
Per #116 there are now explicit action windows between declaring attackers and declaring defenders, and after declaring defenders.

**Comment by cryogen** [comment]
I'm reasonably happy with action windows at the moment until more cards get implemented.  Closing this issue for now.
