### ISSUE TITLE
Robert Baratheon 'blank' STR

### ISSUE THREAD

**Issue by DukeTax** [cryogen/throneteki#280]
Any challenge Robert is involved in, whether alone or with other participants, that sides total strength is calculated as blank. It doesn't even write 0, but is understood as such for the purposes of unopposed. Red Keep was out as well.

**Comment by DukeTax** [comment]
I just had a similar issue with the Red Keep out, where my opponents strength on power challenges was blank. So I'm thinking something is fishy with the Keep atm. :)

**Comment by ystros** [comment]
#283 will fix the Robert issue, will need to look at Red Keep. If your opponent had another character that has dynamic strength (e.g. Drowned Men, Wolf Pup, etc), then it was probably the same issue as Robert.

**Comment by DukeTax** [comment]
It was Tywin. Makes sense then. :)
