### ISSUE TITLE
Stats Tracking (Ench)

### ISSUE THREAD

**Issue by uBaHoB** [cryogen/throneteki#282]
Would be nice if we can see Win/Loss ratio with our decks on the Deck page. Could be tracked only by name of the deck.

**Comment by jbrz** [comment]
That's a pretty big implementation - something the dudes over at jinteki haven't even done now year(s?) down the road.  This is something I think a lot of people would like, but would prefer the client to be fully functional and feature-complete first.

**Comment by cryogen** [comment]
I'd say this is unlikely to happen short term. We already store the stats to make it possible, but there's a whole debate about whether we should publicise them in any fine details
