### ISSUE TITLE
Missing plots.

### ISSUE THREAD

**Issue by uBaHoB** [cryogen/throneteki#29]
I'm not able to see my and opponent plot.
![plots](https://cloud.githubusercontent.com/assets/19303834/20177148/efcdc31e-a753-11e6-860f-4c76a434ba32.png)

**Comment by uBaHoB** [comment]
Also on following turns

![plots 2](https://cloud.githubusercontent.com/assets/19303834/20177393/2e176bba-a755-11e6-98d5-e86ba3265550.png)

**Comment by TheJunik** [comment]
My other concern is that when I hover over a revealed plot card it zooms in on the card below it (if any). From those small pictures I cannot sometimes recognize what the opponent's plot is.

**Comment by cryogen** [comment]
There's a pull request in to fix this, I just need to review it and merge it

**Comment by cryogen** [comment]
Fixed in 17d4c7a2fab5478fa4b7d7e43c227e549cc652a0
