### ISSUE TITLE
Shuffle card into deck

### ISSUE THREAD

**Issue by TheJunik** [cryogen/throneteki#31]
Reason: many cards instruct player to shuffle a card into his/her deck.
Examples:
  Benjen Stark - after BS is killed, shuffle him into owner's deck
  Rebuilding - choose 3 cards from discard pile and shuffle into your deck

**Comment by cryogen** [comment]
This can currently be worked around by opening your deck, dragging card into it, then close and shuffle.

Not ideal I know, but FYI

**Comment by cryogen** [comment]
This is now a lot easier that you can drag cards to your deck.  Drag card to card and hit shuffle until the card implementation is done
