### ISSUE TITLE
Characters setting up on bottom row, locations on top

### ISSUE THREAD

**Issue by doomnote** [cryogen/throneteki#38]
If a location is chosen first during setup, it correctly goes to the bottom row. If a character is chosen first, it incorrectly goes to the bottom row. So whichever is chosen first ends up on the bottom row and remains that way for the rest of the game (all characters get marshalled to bottom or vice versa).

**Comment by doomnote** [comment]
If a location is chosen first during setup, it correctly goes to the bottom row. If a character is chosen first, it incorrectly goes to the bottom row. So whichever is chosen first ends up on the bottom row and remains that way for the rest of the game (all characters get marshalled to bottom or vice versa).

**Comment by cryogen** [comment]
Fixed by 1ff4a5b9c7fcfa4e9b9dcb289cf0b7183e1f75f4

**Comment by cryogen** [comment]
Fix isn't deployed yet :)

**Comment by doomnote** [comment]
Lol sorry new to this haha

**Comment by cryogen** [comment]
This should be deployed now
