### ISSUE TITLE
implement A Meager Contribution

### ISSUE THREAD

**Issue by zacchiro** [cryogen/throneteki#383]
The two cards in question are currently not implemented. They should be :)

However, I looked into them, and it's not clear to me they could be implemented without improving existing events.

In particular, there is an event onStatChanged that will trigger with argument "gold", and in which a trigger for White Tree could be hooked. But that even doesn't say whether it's an increase in gold ("collecting income") or gold being used. How do you want to go about it?
I think it'd be best to add a more high-level event "onCollectIncome", which is fired when addGold is used, but not when removeGold is. Alternatively, we can change all onStatChanged events so that they have as arguments both the old and new value of the stat that did change.

Guidance welcome,
Cheers.

**Comment by cryogen** [comment]
We talked about this on discord a bit today (are you on there?)

White tree needs a new event to work properly, and A Meager contribution can't be fully implemented at the moment but it can be approximated - but not until we can determine that it's the opponent currently marshalling

**Comment by zacchiro** [comment]
On Wed, Feb 15, 2017 at 11:23:41AM -0800, Stuart Walsh wrote:
> We talked about this on discord a bit today (are you on there?)

I'm in the sense that I got an invitation, yes (and thank you!). But I
haven't yet made a habit of joining there for dev-related discussions.
I'll try harder. (I take there is no IRC gateway for the chat on
discord, right?)

> White tree needs a new event to work properly, and A Meager
> contribution can't be fully implemented at the moment but it can be
> approximated - but not until we can determine that it's the opponent
> currently marshalling

OK, I'll just keep an eye on this issue for when there's a proper
solution for all that (I prefer to focus on lower-hanging fruits for
now...). FWIW, my understanding of A Meager Contribution is that it can
also be used outside the marshaling phase, e.g., during the challenge
phase if you gain money with Tyrion or the like. Which might add further
complexity.

Cheers.

**Comment by zacchiro** [comment]
> FWIW, my understanding of A Meager Contribution is that it can also be used outside the marshaling phase

Scrap that: it's (very) clearly only after collecting income at the beginning of the marshaling phase.

**Comment by cryogen** [comment]
There is an IRC gateway now..

irc.oftc.net #throneteki :)

**Comment by cryogen** [comment]
the event is there and white tree is done
