### ISSUE TITLE
Attachments lost, moved to wrong discard or unable to move

### ISSUE THREAD

**Issue by TheJunik** [cryogen/throneteki#39]
1) When a character with an attachment leaves play that attachment disappears from the game (happened with Crown of gold)
2) Confiscation - when removing opponent's attachment from my character that attachment is moved to my discard pile instead of its owner's discard pile (happened with Milk of the poppy)
3) Attachments once attached cannot be moved manually to other play areas, discard pile, hand, etc. (happened with Stinking drunk)

**Comment by cryogen** [comment]
This should now be fixed
