### ISSUE TITLE
highlight not implemented cards in deck lists

### ISSUE THREAD

**Issue by zacchiro** [cryogen/throneteki#394]
The idea of this feature request is to give users some visual clues (e.g., a little "warning" symbol) about cards they have put in their deck that are not (fully?) implemented in Throneteki.

This is something I've proposed in the past on the main chat. @cryogen counter-argued that it is easier to implement the missing cards than to implement this feature, which is a very fair point. However it recently occurred to me that, as a Throneteki player who is also a code contributor, it will help me personally immensely to have this kind of feature, as it will allow me to immediately focus on implementing missing cards that I care about, rather than stumbling upon them while I play.

It might even be the case that this kind of visual clue will encourage other coder/players to make the leap and send their first code contribution that implement the card they want to play. (Dunno, maybe the warning sign could point to the pull request page on GitHub, or something similar.)

If you're still convinced that this is not worth it, that's totally fine. Just close this and we will keep around as wontfix information that others might be pointed to in the future. And sorry for the noise :-)

If OTOH you think it might be worth it, we can use this issue to coordinate the needed work.

**Comment by ystros** [comment]
I've thought about putting this in (or something similar) in the past and think it's superior to maintaining the separate implemented cards spreadsheet. It would also be a useful gauge for players to know what they may be expected to do manually in a game vs what is automated. This would help eliminate confusion about whether cards are broken or just not implemented.

That said, we've been tearing through cards so quickly that it will only be of value for so much longer. It could still be of use for upcoming packs we haven't implemented (the cards are pulled from ThronesDB usually quite a bit before we actually implement them), but that's less of an issue.

I could go either way on this.

**Comment by cryogen** [comment]
There's so few cards not implemented, I don't think this is particularly useful now
