### ISSUE TITLE
Queen Cersei Lanister

### ISSUE THREAD

**Issue by uBaHoB** [cryogen/throneteki#403]
Queen Cersei (http://thronesdb.com/card/05001) is currently implemented incorrect. She reacts to each card being discarded and not as a whole. If opponent discards 2 cards at once Wardens or 2 claim she will get only 1 power.

The example is with manually resolving Wardens of the West (http://thronesdb.com/card/02030), and that may be the issue here. 

![untitled](https://cloud.githubusercontent.com/assets/19303834/23064502/15a85b40-f519-11e6-826c-492fa991a864.png)

You can clearly see that she got power for each card discarded and not the discard as a whole. 

Cheers,

**Comment by cryogen** [comment]
Duplicate of #184
