### ISSUE TITLE
support for immunity to game effects

### ISSUE THREAD

**Issue by zacchiro** [cryogen/throneteki#414]
[Several cards](https://thronesdb.com/find?q=x%3A%22immune+to%22&sort=name&view=spoiler) support some sort of immunity to some or all game effects. In the current meta we have at least the following occurrences of this:
- immune to opponents' events
- immune to Omen card effects
- immune to opponent's character abilities
- immune to opponents' plot effects
- immune to card effects
- immune to opponents' triggered effects
- immune to events
- cannot be knelt by card effects (Ygritte)
- cannot be killed (The Eyrie)

We need a generic mechanism to:
1) allow cards to declare what they are immune it, possibly temporarily
2) allow game effects (or their enacters) to query target cards for immunity and skip effect application if so

The main difficulty is that immunity seems in most cases to be dependent on who is the origin of the effect (as type of card and possibly its controller). This gets in the way of the current style of coding cards where card implementations directly do calls like `player.killCharacter(card)` without passing around the information about *who* is commanding the kill.
That will need to be reworked, by either passing around "this" as event originator where needed, or by passing through a higher-level of abstraction that will check immunity before actually delivering the effect.

This is going to be ~~a pain~~ fun :-)

**Comment by ystros** [comment]
In terms of *providing* the immunity, we'll need to introduce a new effect (or set of effects). Since immunity is provided by card text, can be provided from one card onto another (e.g. Maester Luwin giving Bran "immunity to plot effects"), and can be blanked like other abilities, it can be activated like any other effect.

We should probably code it such that there's a generic effect that takes a function w/ parameters for the source card and the type of ability it is ('action', 'reaction', etc). With the generic one in place we can write effects that use it for the more common cases.

Some potential examples:

```javascript
// Craster
this.persistentEffect({
    match: this,
    effect: ability.effects.immuneTo((source, type) => source.hasTrait('Omen'))
});

// Maester Luwin
this.persistentEffect({
    match: (card) => card.name === 'Bran Stark',
    effect: ability.effects.immuneToPlotEffects()
});
```

These effects should push the appropriate immunity function onto an array on the card (since you could potentially get multiple immunities). Then whatever method that does the kill (or any other action that is subject to immunity) can exclude any cards who has an immunity function that returns true.

```javascript
class DrawCard {
    isImmune(source, type) {
        return _.any(this.immunities, immunity => immunity(source, type));
    }
}

// The thing doing the kill
if(card.isImmune(this.source, this.type)) {
    return;
}

// do the kill
```

(This is all of course the easy part)

**Comment by zacchiro** [comment]
For added "fun", my understanding of the [Target](http://thronesdb.com/rulesreference#Target) and [Immune](http://thronesdb.com/rulesreference#Immune) rules is that you cannot choose an immune card as target for some ability. In terms of best possible Throneteki gaming experience, that would mean that immunity should be taken into account also when:
- `condition` predicates are checked
- `promptForSelect()` is used, to disallow choosing immune cards

(there might be more cases like these)

In terms of coding, we certainly want to avoid having to manually check immunity in all occurrences of the above cases. So it should be handled by the game framework.

**Comment by zacchiro** [comment]
Here's a wacky idea: maintaining a stack of the cards whose effects are currently being resolved. A card get pushed on the stack when one of its ability is triggered and removed after the effect has been completely resolved. In its most general form it needs to be a stack due to [Nested Ability Sequence](http://thronesdb.com/rulesreference#Nested_Ability_Sequences).

The stack will be modified only by the core game engine itself. The implementation of individual effects will be allowed only read-access to the stack. But that should be enough for methods like killCharacter() (or any other effect-implementing method, really) to check if the target card is immune to effect coming from the currently topmost card on the stack.

This will remove the need of passing around the origin of effects everywhere, starting from card implementations.

And yes, it is stateful. But it is a state that is maintained only by the Throneteki kernel. Everything else access it read-only, so it shouldn't introduce nasty side-effects everywhere.

Thoughts?

**Comment by ystros** [comment]
Hmm. A stack like that may actually work. With the introduction of the `cost` property on actions / reactions, all non-effect abilities go through `AbilityResolver` now. That would be the perfect entry point to push / pop from the stack. Then, as you said, methods that need to check immunity can look at the top of the stack. There may be some edge cases where the effects engine may need to modify the stack (mostly the 'at end of phase, kill this character' type effects), but we may be able to work around those.

re: targeting + immunity, I'm probably going to attempt adding a `target` property on actions / reactions. This should clean up a LOT of repeated usages of `this.game.promptForSelect()` and allow us to centralize immunity rules for targeting.

**Comment by zacchiro** [comment]
With All Men Are Fools there's now a new use case (which I've added to the first comment here): "Ygritte cannot be knelt by card effects". This makes immunity conditional to what the effect actually does — kneeling the card in Ygritte's case.

**Comment by zacchiro** [comment]
@ystros so are you officially sold on the stack idea?

**Comment by zacchiro** [comment]
Added The Eyrie as use case, with its "Until the end of the phase, that character cannot be killed."

**Comment by ystros** [comment]
@zacchiro Per your suggestion, I think the way forward here will be to consolidate 'cannot' effects with 'immunity' (Ygritte seems to make this mandatory).

As far as I can tell, the main difference seems to be that 'cannot' specifies a specific thing that isn't allowed, while 'immune' specifies the cards not allowed to affect the current card. Ygritte is weird in that it specifies both (kneel from card effects) despite using 'cannot.'

```
            Effect      Effect source
immunity:   all         X
cannot:     X           cards or framework
Bran+Luwin: all         opponent plots
Eyrie:      kill        cards or framework
Craster:    all         Omen cards
Ygritte:    kneel       cards only
```

If we use this basic framework, we could also add a property to card select prompts to specify the effect type that will automatically filter out immune/cannot X cards.

I still think the stack is our best bet, but am unsure about what edge cases may crop up. For example, immunity does not prevent a thing from happening if it's part of a cost, only effects. So with the stack you may have to worry about scenarios where one card ability triggers which then mid-effect triggers another interrupt/reaction that requires an immune card to pay a cost. The immune card would see the previous card at the top of the stack thereby preventing the cost from being paid. I can't think of a scenario in which this is possible currently, but it seems like it will be possible.

Having typed all of this, I just realized another important difference between 'cannot' and 'immune': cannot is absolute, so they can't be used for that type of cost at all, whereas immune cards could be. That means things are a bit trickier but there's still a bunch of overlap between the two concepts.

**Comment by cryogen** [comment]
Closing this as it's either done or able to be done now :+1: :)
