### ISSUE TITLE
Adding glow / pulse effect to selectable cards

### ISSUE THREAD

**Issue by ystros** [cryogen/throneteki#422]
In terms of making it more clear what can be selected during a select card prompt, I propose we add some sort of glow and/or pulse effect on cards that can be selected. This may reduce incidents of clicking on and kneeling something you think should be selectable but due to changes in game state are not (e.g. you missed a message where a character was bypassed by stealth). Selecting a card would have the same styling it has currently and it would stop glowing.

I have this working locally but thought I'd open a discussion issue before just PRing it. It would work with any card select prompt but I've demonstrated it here with challenges.

![feb-18-2017 23-59-13](https://cloud.githubusercontent.com/assets/145077/23100471/75b907d2-f636-11e6-8b99-ec4836bb22a6.gif)

This can be made more subtle, more obvious, different color, etc.

Is this something that would be beneficial?

**Comment by khyinn** [comment]
Really good. This is something that makes the UI more polished and don't break anything so why not adding it :) I think the glowing effect is just good as it is. Talking about colors, why not making some custom colors for actions like green for intrigue challenges, red for military, blue for power and yellow for "standard" ? Just an idea...

**Comment by cryogen** [comment]
I like the idea, have wanted something similar for a while, not sure about the colour/intensity.  Think the colour may be too similar to the selection colour, though I appreciate that's probably why you picked it

**Comment by ystros** [comment]
@khyinn I think the multiple colors may be a bit too much. We do so many of these highlighting effects (highlighting new cards, cards in the challenge, cards bypassed with stealth, taken control cards, etc) that I'd want to avoid introducing things that could be confused with those.

@cryogen I indeed picked it to be close to the selection color, since the idea is it resolves into the selection when clicked. It may be too close at the moment though. I'll play around with it before I PR.

**Comment by khyinn** [comment]
@ystros OK, you're right, that will probably be too much.
