### ISSUE TITLE
Warnings from npm install

### ISSUE THREAD

**Issue by khyinn** [cryogen/throneteki#424]
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated husl@5.0.3: Project renamed to HSLuv

I think this can easily be fixed :)

**Comment by cryogen** [comment]
Most of these are generated by dependencies rather than by packages we use directly, so there's not a lot we can do about it
