### ISSUE TITLE
Chat Window Froze up During Play

### ISSUE THREAD

**Issue by euphius** [cryogen/throneteki#475]
Chat window froze during a military claim being taken.  No further typing was received and no further in game messages were displayed the rest of the way through game completion. 
While I am writing, things to consider for game improvements.  Actions after defenders are declared are only given 1 per player rather than until both players pass like the other action windows correctly do.  Does not give attackers a chance to respond after a defender uses an action.  
Likewise, a reaction window is needed pre-claim for defenders.  Cards like Viper Eyes are nearly impossible to play in their correct window.  Reactions to losing are a game mechanic and right now they have no place in which to use them. 
Great game and hoping to see it keep improving!

**Comment by zacchiro** [comment]
Do you remember when did this happen (e.g., hour of the day) and/or how many games in total where ongoing at the time?
If it happened at peak time, this might just be a side-effect of high server load (which is already being worked on).

**Comment by euphius** [comment]
I sent the report within a few minutes of when thr game ended (had to find
and sign up for the issue report site).
Several days later I cannot remember if it was a time where there were
10-15 games or 16-25.

Todd

**Comment by cryogen** [comment]
I'm pretty sure this is "just" a result of triggering a server error.  I don't think it is its own issue that needs to be investigated separately.
