### ISSUE TITLE
Cannot remove attachments

### ISSUE THREAD

**Issue by MacrobiusTebo** [cryogen/throneteki#49]
Example: when Viserys leaves play, he can remove an attachment. You can't do it manually.
Also, When a character or leaves play, the non-terminal attachments disappear.

**Comment by MacrobiusTebo** [comment]
Cannot look at a certain number of cards (like for Summons).

**Comment by MacrobiusTebo** [comment]
Cannot do a second challenge of the same type. Like a second military with Khal Drogo out.

**Comment by cryogen** [comment]
Attachments can now be removed from play, the others will be implemented as those cards get implemented
