### ISSUE TITLE
Kneeling Daenerys to play Dracarys! should immediately remove the -1 strength ability from her standing.

### ISSUE THREAD

**Issue by AisoRed** [cryogen/throneteki#543]
Jaime Lannister (Core) is participating on the opponent's side and Daenerys Targaryen is standing on my side. Jaime enters a military challenge and his strength is reduced from 5 to 4. I kneel Daenerys to play Dracarys! to reduce Jaime's strength by 4 until the end of the phase. Because Daenerys is now kneeling, Jaime's strength should be at 1, however the system immediately killed Jaime.

**Comment by cryogen** [comment]
@ystros Is this still a thing?

**Comment by ystros** [comment]
@cryogen Yes, fairly certain this is still a problem (if not this specific scenario then similar ones for sure). It stems from it mattering the order effects are applied / checked, which is something we don't support currently. Things like `Effects.killByStrength` need to be checked only after everything else has already been applied or unapplied.
