### ISSUE TITLE
Infinite marching to the wall

### ISSUE THREAD

**Issue by DukeTax** [cryogen/throneteki#60]
On two separate occasions, marched to the wall kept triggering until almost every character on both sides of the board was discarded, followed by a game crash.

**Comment by cryogen** [comment]
Were both side using the same plot?  Can you give any further information on what led to this?

**Comment by DukeTax** [comment]
Both times only one side played marched. Basically it prompted me to trigger my plot, forcing me to choose a character to discard, followed by the same for my opponent. Then it prompted me to trigger my plot again. Repeat.

**Comment by cryogen** [comment]
This should now be fixed
