### ISSUE TITLE
Site doesn't respond

### ISSUE THREAD

**Issue by aufruf** [cryogen/throneteki#610]
Hi there,

Having a strange issue since new version released.

After clearing the cache didn't work I have re-installed Firefox yesterday and was able to play a game. So In general, the setup (Computer / Firewall etc.) should work and did with the old code. 

Logging in today and now the site seems to not response. Same behavior as before the re-install: 

I am logging in and I am able to see my decks. I can not chat (entering text and pressing send but it does not appear). I can not spectate (pressing "Watch" but nothing happens). If I try to create a game the window pops up to enter the name etc. but then I can't launch it. 

Sorry to post it here but as I said, chat doesn't work :)

Thanks for all the good work!

**Comment by aufruf** [comment]
I just realized: The behavior described above is actually the same if I haven't logged in at all. However, I can see my decks. Hope this helps.

**Comment by aufruf** [comment]
Now it get's interesting: Re-Installed Firefox again. Opend the site and was logged in?? Can also join a game and spectate. Is there something with double logins?

**Comment by cryogen** [comment]
It's a bit weird that you're having to reinstall firefox.  If it happens again, can you try to clear your cookies rather than reinstalling?

**Comment by aufruf** [comment]
Having the same problem again. Neither clearing cache / cookies nor reinstall currently works. Strange. Worked two hours ago - then I logged out and now as described above. I remember that you mentioned last week something regarding firewalls. Anything I need to do there?

**Comment by aufruf** [comment]
Just tried it with my iPhone over UMTS (so no internal firewalls etc) but same problem..

**Comment by cryogen** [comment]
This is a bit weird.  Can you try something for me?  Hit f12 to get the debugging options, to go the network tab.  Then refresh the page, and then click line at the top that says GET / (on the left hand side in my screenshot) and then click the response tab (Right hand side in my screenshot)

Then scroll the window do try and find the same text as in my screenshot:

![image](https://cloud.githubusercontent.com/assets/1053365/24044185/28ed7640-0b12-11e7-925f-7c60ebcaa07a.png)

Let me know what it says

**Comment by aufruf** [comment]
First, thanks that you take some of your time for this. Attached the requested screenshot: ![Screenshot](https://picload.org/image/rliggowl/bildschirmfoto2017-03-17um15.1.png)

**Comment by cryogen** [comment]
Odd, that suggests that it's working, or at the very least you are authenticated.  You still can't chat in the lobby?

**Comment by cryogen** [comment]
I think we fixed this on the site itself, please reopen if still having issues :)
