### ISSUE TITLE
Renly Baratheon (FFH) should not offer to draw a card upon non-loyal draw

### ISSUE THREAD

**Issue by mplain** [cryogen/throneteki#612]
Renly's ability triggers each time you draw a card using insight, even if you drew a non-loyal card, asking Yes or No. Suggest greying out the Yes button if you drew a non-loyal. Less confusion that way.

**Comment by zacchiro** [comment]
Just wanted to mention that the dialog window is there to avoid revealing game state to your opponent if you don't want to reveal the first drawn card. But you're right that it might be confusing for Renly's controller in the current form. We should probably offer a reveal/pass choice, or something such.

**Comment by cryogen** [comment]
This card no longer prompts so this issue is no longer valid.  (that fact that it leaks information is another separate issue that's im pretending doesnt exist atm)
