### ISSUE TITLE
Putting cards into play outside of marshalling

### ISSUE THREAD

**Issue by OniNoOdori** [cryogen/throneteki#62]
At the moment you can manually put characters and locations into play during marshalling by dragging them onto the field. However, you can't do so during challenges. This is crucial for cards like Arianne or the new Moon Brothers. I would appreciate, if this could be fixed.

Also, you can kneel almost everything except for the faction card. This requires only a small fix, and would make cards like I Never Bet Against My Family usable... well, maybe not THAT card, but you get the idea.

Thank you for developing this software. It already looks very slick.

**Comment by cryogen** [comment]
For faction card, see #46 - the other one seems like a valid bug though

**Comment by cryogen** [comment]
I'm pretty sure this is no longer an issue, closing
