### ISSUE TITLE
Selyse Baratheon v. Nymeria Sand - cannot obtain back intrigue icon

### ISSUE THREAD

**Issue by zacchiro** [cryogen/throneteki#639]
bug i just noticed in a game:
- Nymeria is used to remove a INT icon from Selyse
- Selyse action is used to give her a INT icon *back*
the latter doesn't work, and Selyse remains without a INT icon and cannot initiate such a challenge.
Trying to use /give-icon on her didn't work either

**Comment by zacchiro** [comment]
and to make things more interesting: Selyse was returned to hand using Ghaston Grey. When, turns later, she was put back into play, she was still *without* the INT icon, with no way of giving the icon back to her with /give-icon

**Comment by ystros** [comment]
The implementation was overriding `addIcon` which meant any attempt to give Selyse an icon - through her ability, through another characters effect, through the chat commands - would fail and instead call the action method. It's also why she didn't gain it back when returned to hand - the unapply for the `removeIcon` effect calls, `Card.addIcon`, which would again just trigger her prompt.
