### ISSUE TITLE
Enhancement: join back to the game after connection failure

### ISSUE THREAD

**Issue by TheJunik** [cryogen/throneteki#64]
Quite often it happens that a player is disconnected because of a connection failure. Allow for him/her to join back to the game. 

Keep the state of the game upon disconnection (other than through Leave button) while the opponent is still in the game. It is up to the player whether he wants to keep waiting for the disconnected player or leaves the game. It could be a new command (/rejoin, /reconnect) or a new button and the connection is then restored and the game can continue.

**Comment by MacrobiusTebo** [comment]
Yes, this has happened to me several times and there is no way to get back in game. It's frustrating because my connection comes back after less than a minute but I still can't get back in. It makes feel bad that that drops the game.
