### ISSUE TITLE
Reducers regression: cannot undo the reduction by standing a card manually

### ISSUE THREAD

**Issue by mplain** [cryogen/throneteki#648]
Suggestion: when a user manually clicks a kneeling discounter chud or location, check and remove the discount that is "floating in the air" (preferrably the discount applied by this specific loc/char). Something like this:

On click:
- if standing, kneel and give 1 discount
- if kneeling, stand and remove 1 discount

Some effects stand chars and locations, but those are used via card abilities. If a user manually stands a loc or char by clicking them, I think it's a safe bet to assume that they want to undo the discount.

**Comment by cryogen** [comment]
This is less of a suggestion and more of a bug.  It used to work this way, something has gotten broken
