### ISSUE TITLE
Enhancement: browser notification when player joins game

### ISSUE THREAD

**Issue by GARLICDOG** [cryogen/throneteki#67]
Right now the game has a small player base, that sets back the testing too. I have only played it when I found someone to join. The one time I got someone to join my game I was checking the tab every minute or so which became a little tedious. Is there a way you could add a notification so as to make it easier for people to start games, I think it would make it easier in the beginning for players to create games.

**Comment by doomnote** [comment]
If you have your sound on it plays a trumpet sound when someone joins your lobby

**Comment by cryogen** [comment]
As doomnote says, there is already a notification (a rather annoying one)
