### ISSUE TITLE
Benjen triggers twice with one copy in hand and one in play

### ISSUE THREAD

**Issue by zacchiro** [cryogen/throneteki#678]
Happened to me yesterday: had 1 copy of Benjen in play and 1 in hand. The one in play dies, i got prompted to trigger his ability and I do. After that, I got prompted a second time. I denied the trigger,but I suspect it was the copy in hand triggering.

**Comment by ystros** [comment]
Haven't been able to reproduce this locally or through a test. Take a look to see if #679 accurately describes your scenario (1 Benjen in hand, 1 Benjen in play, Benjen dies)

**Comment by zacchiro** [comment]
On Sat, Mar 25, 2017 at 10:06:57AM -0700, Brian Upton wrote:
> Haven't been able to reproduce this locally or through a test. Take a
> look to see if #679 accurately describes your scenario (1 Benjen in
> hand, 1 Benjen in play, Benjen dies)

It does, but unfortunately I don't remember how Benjen died. I have a
feeling it was not MIL claim, but I don't remember what exactly. Do you
feel that difference might be relevant here?

-- 
Stefano Zacchiroli . zack@upsilon.cc . upsilon.cc/zack . . o . . . o . o
Computer Science Professor . CTO Software Heritage . . . . . o . . . o o
Former Debian Project Leader . OSI Board Director  . . . o o o . . . o .
« the first rule of tautology club is the first rule of tautology club »

**Comment by ystros** [comment]
Thanks for the additional info. I tried adding tests around other ways Benjen may be killed - during the plot phase w/ Valar, and through card abilities (in this case using GoH Joffrey):
https://github.com/ystros/throneteki/commit/3fee06b8b3927753a27f95fb9419ab1111735f46

Sadly, still haven't been able to reproduce the double trigger.

**Comment by zacchiro** [comment]
On Mon, Mar 27, 2017 at 12:03:26PM -0700, Brian Upton wrote:
> Thanks for the additional info. I tried adding tests around other ways Benjen may be killed - during the plot phase w/ Valar, and through card abilities (in this case using GoH Joffrey):
> https://github.com/ystros/throneteki/commit/3fee06b8b3927753a27f95fb9419ab1111735f46
> 
> Sadly, still haven't been able to reproduce the double trigger.

Feel free to close as unreproducible. It definitely happened :-), but we
can certainly wait for a reliable test case to worry about this.

**Comment by ystros** [comment]
Per our discussion in Discord about the similar problem with Bastard Daughter vs Blood of the Dragon, I suspect your Benjen was killed by a burn effect, which does seem to trigger twice inappropriately.

**Comment by zacchiro** [comment]
Yup. Just for the records, the other situation in which this triggered is with Bastard Daugther getting killed by the Blood of the Dragon plot: the controller gets prompted twice about triggering her to make the opponent discard.
