### ISSUE TITLE
Jhogo: TypeError: Cannot read property 'defendingPlayer' of null

### ISSUE THREAD

**Issue by cryogen** [cryogen/throneteki#689]
https://sentry.io/throneteki/throneteki/issues/241977380/

```
TypeError: Cannot read property 'defendingPlayer' of null
  File "/home/stu/throneteki/server/game/cards/characters/02/jhogo.js", line 31, in Jhogo.getNumberOfDeadDefendingCharacters
    this.game.currentChallenge.defendingPlayer.deadPile.each(card => {
  File "/home/stu/throneteki/server/game/cards/characters/02/jhogo.js", line 13, in persistentEffect.effect.ability.effects.dynamicStrength
    effect: ability.effects.dynamicStrength(() => this.getNumberOfDeadDefendingCharacters())
  File "/home/stu/throneteki/server/game/effects.js", line 149, in Object.apply
    context.dynamicStrength[card.uuid] = calculate(card, context) || 0;
  File "/home/stu/throneteki/server/game/effect.js", line 151, in _.each.target
    _.each(this.targets, target => this.effect.apply(target, this.context));
  File "/home/stu/throneteki/server/game/effect.js", line 151, in Effect.setActive
    _.each(this.targets, target => this.effect.apply(target, this.context));
...
(26 additional frame(s) were not displayed)

TypeError: Cannot read property 'defendingPlayer' of null
```

**Comment by cryogen** [comment]
@ystros This seems to be related to the attachments losing their parents bug - it seems that it's possible for things to happen in between condition and effect.  Can we recheck the condition before applying the effect?

**Comment by ystros** [comment]
@cryogen Condition should already be re-checked before applying the effect, which is why this type of error has baffled me. The effects can generate new events that must be resolved before continuing to apply effects but having the challenge object go away mid-effect shouldn't be possible. I looked into Jhogo briefly and couldn't figure out what was wrong. Need to take a closer look overall.

**Comment by cryogen** [comment]
This is still occurring.  Is it possible the dynamic strength is recalculating at a point when there is no challenge anymore? Or should the dynamic strength only recalculate when the condition is matched?  Could a /cancel-prompt mess with this?

**Comment by cryogen** [comment]
https://sentry.io/throneteki/throneteki/issues/271073431/
