### ISSUE TITLE
Player confusion over how to select a plot / Improve touch support

### ISSUE THREAD

**Issue by ystros** [cryogen/throneteki#695]
See: https://sentry.io/throneteki/throneteki/issues/242130202/

These errors are occurring because players are dragging their plot from the plots pile to the used plots pile to try and select their plot, instead of clicking the plot they want and then clicking the done button as designed.

1. Is there a way to make it more clear what the player should be doing when selecting plots?
2. Is there an alternate UI that would alleviate confusion (e.g. a prompt with buttons for each selectable plot instead of clicking the plot and clicking 'Done')
3. Is the drag-drop functionality between the plot and used plot piles useful or needed?

**Comment by cryogen** [comment]
This is more than likely due to how crappy touch support is right now

**Comment by zacchiro** [comment]
I've noticed a similar pattern on card setup and upon marshaling. Granted, most of it is habits of people coming from OCTGN. But @ystros is probably right that there might be ways to make the expected action more evident UI wise.

Also, there is a point where we are inconsistent on this: discarding down to reserve is drag & drop, while everything else in the game does not (except when you need to manually alter game state, that is). It would be probably smart to switch to click based discard also for discard to reserve. (And yes, I understand drag & drop for reserve was in place to make it harder to make mistakes and reveal cards to your opponent, but consistency should be preferred IMO.)

**Comment by DukeTax** [comment]
To add to that: manually discarding multiple cards to reserve could trigger Cersei (Lions) multiple times, when discarding to reserve should be done in a single step (so 1 trigger at most).

**Comment by cryogen** [comment]
#1863 fixes this
