### ISSUE TITLE
after controller change, Devoted Bloodrider gives +1 to the wrong bloodriders

### ISSUE THREAD

**Issue by zacchiro** [cryogen/throneteki#711]
Seen yesterday playing: I marshaled a Devoted Bloodrider from the discard pile of my opponent using Night Gathers. My opponent had bloodriders in play. As a result, both mine (as Devoted controller) and their (as Devoted owner) bloodriders got the +1 strength modifier. Expected behavior is that only mine (as controller) should have been boosted.

**Comment by cryogen** [comment]
Pretty sure this is the same as #569

**Comment by ystros** [comment]
It looks like #569 was an issue with The Kingsroad implementation specifically and not a general take control problem. So this will need to be looked at separately after all.

**Comment by cryogen** [comment]
@ystros having actually looked at the card, it doesn't check for a controller in match(), I believe you said this was unnecessary? So what's the deal here? :)

**Comment by ystros** [comment]
@cryogen I need to look more closely but I think it's an ordering problem in `Player.putIntoPlay`. It calls `card.play` which activates effects, then moves the card into the play area, **then** sets the card's controller to the current player. So when the card effects are activated, it's still controlled by the opponent, thus giving them the bonuses.

**Comment by zacchiro** [comment]
I've noticed this today also on a House of the Undying trigger. Of course it's the same situation, so nothing really new here.
FWIW, I like the card implementation as it is, i.e., we really want persistent effect to apply by default to the current controller, without needing any special gymnastic when controller != owner.
