### ISSUE TITLE
Adding a '.' to the TLD stops the CORS rules matching successfully

### ISSUE THREAD

**Issue by Hyoux** [cryogen/throneteki#715]
I can't launch, join or watch any game since 2 week. When i try, i see some pop-up saying

Reconnecting
Attempt number 2 to reconnect..

✕
Connect Error
There was an error connecting to the game server: xhr poll error(400)

It appends since i have a connection problem during a game.

(Sorry if i use the GitHub tools badly...)

**Comment by cryogen** [comment]
What is the exact url you are using to access the site?

**Comment by Hyoux** [comment]
http://throneteki.net./play

**Comment by cryogen** [comment]
Ok, lose the extra dot on the end and you should be good to go

**Comment by Hyoux** [comment]
Less than 45 seconds to fix the problem, thanks Cryogen !

**Comment by cryogen** [comment]
No problem

**Comment by cryogen** [comment]
This is no longer an issue because of the switch to  using paths instead of ports
