### ISSUE TITLE
Iron Fleet Scout prompt says '+1 strength' even if first player

### ISSUE THREAD

**Issue by doomnote** [cryogen/throneteki#721]
It does apply +2 correctly - just a typo in the prompt

**Comment by zacchiro** [comment]
The card code is coherent in the strength boost it gives and the prompt. So either in this case it actually gave +1 and the bug report is incorrect, or there was *another* reason for the applied modifier to be +2.

**Comment by DukeTax** [comment]
It's just the label shows +1 independent of being the first player. :)
