### ISSUE TITLE
Northern Refugee's cost is not decreased by Winter plots

### ISSUE THREAD

**Issue by AKWolff037** [cryogen/throneteki#734]
Northern Refugee still marshals at full cost even when a Winter plot is revealed.

**Comment by DukeTax** [comment]
Not a real issue, Northern Refugee is not implemented as per the card implementation status: https://docs.google.com/spreadsheets/d/1t7ITlfkaUvso30QEZIbqswv3FM0N95UtWc-RDtPLdIQ/edit#gid=1047857291

**Comment by zacchiro** [comment]
so this issue should be renamed to something like "implement Northern Refugee" :)

**Comment by cryogen** [comment]
Northen Refugee is not currently implemented, as already stated
