### ISSUE TITLE
Request: Win% stats tracking

### ISSUE THREAD

**Issue by milchteee** [cryogen/throneteki#784]
Hey cryogen! I was hoping to be able to see my own personal stats as far as win% goes. If not, then perhaps could you include win% in your occasional 'monthly' reports on gist.github? Thanks a lot!

(I'm a tryhard who wants to know my win% and how it stacks up to others!)

**Comment by cryogen** [comment]
It's unlikely that this will get done, but I have added the percentage to the monthly stats
