### ISSUE TITLE
varys riddle v. calm over westeros: claim reduction doesn't apply

### ISSUE THREAD

**Issue by zacchiro** [cryogen/throneteki#812]
Experienced the other day in a game where i was playing: my opponent opens with clam over westeros, i open with vary's riddle. He reduces military claim, i reduce intrigue. During my challenge phase, my claim value was set to 1, rather than 0 as it should have been.

**Comment by ystros** [comment]
To be clear, the full claim was applied for the reduced challenge types when it shouldn't have been?

UI-wise I think it will say that you have 1 claim in the player summary box, even though it actually applies 0 claim for the specific challenge type. (At least in terms of how Calm Over Westeros normally works - wouldn't be surprised that Varys doesn't clone it properly).

**Comment by zacchiro** [comment]
On Wed, Apr 26, 2017 at 10:05:49AM -0700, Brian Upton wrote:
> To be clear, the full claim was applied for the reduced challenge
> types when it shouldn't have been?

Yes, both the claim value in the UI was 1 *and* the opponent was asked
to satisfy the claim while they shouldn't have been, so had to cancel
claim application.

Cheers.
-- 
Stefano Zacchiroli . zack@upsilon.cc . upsilon.cc/zack . . o . . . o . o
Computer Science Professor . CTO Software Heritage . . . . . o . . . o o
Former Debian Project Leader . OSI Board Director  . . . o o o . . . o .
« the first rule of tautology club is the first rule of tautology club »

**Comment by zacchiro** [comment]
On Fri, Apr 28, 2017 at 12:20:59AM -0700, Stuart Walsh wrote:
> Closed #812 via #822.

Thanks!
