### ISSUE TITLE
margaery tyrell (AMAF) triggers on valar

### ISSUE THREAD

**Issue by kitoxme** [cryogen/throneteki#819]
hello, currently margaery tyrell (AMAF) triggers on valar even when she dies
according to the rules of the game in order to react to a lord/king dead she must survive the valar 
i think this issue is related to the fact that the game kills characters one by one and not simultaneously
related to this: we can't order the characters that die on valar turns (the order they go to dead pile) wich is relevant in ghost of harrenhall plots.

hope this gets fixed soon,
thanks, you are doing a great job!

**Comment by ystros** [comment]
Thanks for the report! The simultaneous kill problem should be fixed once #811 is merged.

**Comment by ystros** [comment]
This has been merged and deployed, should be fixed now.
