### ISSUE TITLE
Some attachments placed in setup double their effect

### ISSUE THREAD

**Issue by ystros** [cryogen/throneteki#833]
When some attachments are placed during setup, it grants whatever its effect twice.

For example, if a Valyrian Steel Dagger is attached to a character during setup, that character will get +4 STR during intrigue challenges. If it is attached any other time, they will get the proper +2 STR bonus.

This may be a result of the `onCardEntersPlay` event being fired twice for attachments during setup - once when placed, then again when attached. However, if that were the only cause I would expect all attachments in setup to have the same problem and they don't seem to.

**Comment by Ecth3lion** [comment]
Happened to me too vs NW with the +2 str during challenges dagger every other marshalled atchment worked fine.
