### ISSUE TITLE
Lord Renly's Ride does not add strength

### ISSUE THREAD

**Issue by HouseCatofWar** [cryogen/throneteki#840]
I tried playing Lord Renly's Ride with Rattleshirt's Raiders in my dead pile. The card was played and went straight to the discard pile without giving me the option to target it. My character neither gained strength nor intimidate.

**Comment by ystros** [comment]
Lord Renly's Ride has been implemented in #827 but hasn't been deployed on the site yet. It should work as intended once deployed. Thanks!

**Comment by HouseCatofWar** [comment]
Great, thanks!
