### ISSUE TITLE
winter festival interrupt

### ISSUE THREAD

**Issue by kitoxme** [cryogen/throneteki#842]
i was playing a game where i revealed a winter festival plot and i'm at 13 power. during challenges my eddard stark (with 5 or 6 power on him) gets a poison token by tyene sand, so it will die AT the end of the phase, but winter festival will interrupt first, winning the game for me. What happens is that the game kill my eddard first and then triggers winter festival, wich is not correct (see WUA rule on official FAQ).
is this fixable ??

thank you

**Comment by ystros** [comment]
Thanks for the report! We do enforce the phase ending vs at the end of phase effects already. 

I've created a test to mirror this scenario in #843 and unfortunately wasn't able to reproduce the issue. Winter's Festival seems to be triggering at the appropriate time, before Tyene's poison kills Eddard.

Did there happen to be a Summer plot out on the same round as Winter Festival (which would have prevented it from triggering)? Or were there any other kill effects out beside Tyene's poison?

**Comment by kitoxme** [comment]
i don't recall a summer plot or any other effects, maybe i was missing something else that game. Anyway is good to know you reproduced the scenario and was working fine, thanks.

cheers
