### ISSUE TITLE
Strength not recalculated when control is modified

### ISSUE THREAD

**Issue by AKWolff037** [cryogen/throneteki#845]
Situation: Opponent had Ser Mallister in play with The Wall, boosting his strength to 5.  I played Ward on him to take control, and his strength was still set to 5 and had to be manually adjusted.

**Comment by ystros** [comment]
Similar to #711 and #756 but may be separate, so leaving this open.

**Comment by ystros** [comment]
Note to @cryogen - #959 explicitly does not fix this issue, only when a controlled card is put into play or the card generating the effect changes control. It does not address a card *receiving* an effect changing control.
