### ISSUE TITLE
[Suggestion] Ask for controller's permission to kill/discard a card

### ISSUE THREAD

**Issue by mplain** [cryogen/throneteki#850]
Any effect that attempts to kill or discard a card from play should prompt a pop-up window asking that card's controller for his permission to proceed, in case he has a cancel or a save.

**Comment by cryogen** [comment]
The cancel or save should be the preventing measure.  We need to implement those cancel/saves, rather than adding fudges like this, imo

**Comment by mplain** [comment]
Yeah but when? Temporary measures are better than no measures at all, right?

**Comment by cryogen** [comment]
Depends.  What cards are causing you trouble?  If it's easier to do the cards than this workaround, better to spend the effort doing the cards

**Comment by mplain** [comment]
Varys. After challenges I press "Varys" in the pop-up window, tables is wiped immediately, then my opponent yells "Treachery!"

**Comment by cryogen** [comment]
So what you're saying is we need Treachery! implemented, stat - Good thing that's the next thing I'm looking at!

**Comment by mplain** [comment]
Well, my suggestion is to implement a simple temporary fix while you're working on a more permanent solution. FWIW.

**Comment by zacchiro** [comment]
(The problem with temporary solutions v. limited development time, is that they just postpone proper fixes, *especially* when they are just around the corner.)

Speaking of which, now most of the cancels have been implemented (thanks to @cryogen / @ystros).
Are you then OK with closing this issue, @mplain ?

**Comment by mplain** [comment]
As you wish.

**Comment by zacchiro** [comment]
It was a honest question: are you happy with the current state of cancels or not?
(also, i can't close the issue myself, but as submitter you should be able to — if appropriate)

**Comment by mplain** [comment]
I haven't played for a couple days, haven't seen the currect state of things. I'll close the issue now.
