### ISSUE TITLE
Implement Barring the Gates

### ISSUE THREAD

**Issue by Ecth3lion** [cryogen/throneteki#856]
Interactions such as Ghosts of Harrenhal and Harrenhal itself are not stopped by Barring the gates 
Furthermore i believe that ambush works as well but hasn't come across such a case yet. 

(Easy to work around but automation is nice too) ^_^

**Comment by ystros** [comment]
Barring the Gates isn't currently implemented, hence why it isn't working. ;-)

**Comment by cryogen** [comment]
As stated, this card is not implemented - would rather not have open issues for every card that isn't implemented as we already have the implementation status doc.  Thanks!
