### ISSUE TITLE
Silent Sisters v. Blood of the Dragon

### ISSUE THREAD

**Issue by zacchiro** [cryogen/throneteki#868]
[ seen [reported](http://letronedeferjce.forumactif.com/t18924-silent-sisters-blood-of-the-dragon#417881) on the french agot forum ]

- Blood of the Dragon is currently revealed as a plot
- Silent Sisters enters play with more than one characters in its owner dead pile (8, in this specific case)
- Silent Sisters dies immediately, while they shouldn't, as the two constant abilities act contemporarily

**Comment by cryogen** [comment]
Similar to #543

**Comment by zacchiro** [comment]
right, @ystros' comment there seems to be the deal here:
> Things like Effects.killByStrength need to be checked only after everything else has already been applied or unapplied.

**Comment by ystros** [comment]
I have no reason to believe this has been fixed but I'm having trouble reproducing it now (along with other burn problems)

**Comment by zacchiro** [comment]
Seen in the wild again with a different incarnation (possibly easier to reproduce): The Wall on table, Blood of the Dragon revealed, Messenger Raven is marshalled and dies immediately.

**Comment by ystros** [comment]
Question if you can remember - which player created the game (Targ or NW) and which player was first player at the time?
