### ISSUE TITLE
Duplicate games

### ISSUE THREAD

**Issue by ystros** [cryogen/throneteki#88]
A bunch of duplicate games seem to have been created. I tried asking in chat to get more details from the players as to what happened but haven't seen a response yet.

![screen shot 2016-11-27 at 9 44 18 am](https://cloud.githubusercontent.com/assets/145077/20650694/a4c5880a-b489-11e6-9ef8-dcd424218752.png)

**Comment by cryogen** [comment]
This should no longer be possible
