### ISSUE TITLE
Errors on calculating attacking characters strength (when playing lord of the crossing ?)

### ISSUE THREAD

**Issue by silme39** [cryogen/throneteki#898]
Hello ! 

Great work on throneteki ! A very impressive way to play online ! Congrats ! You havze done an outstanding job here ! 

Yesterday we experienced problems on three consecutive games (games played between Silme and Nevevar beginning around 9 o clock in the evening if this could help). 

I was playing targaryen Lord of the crossing agenda and whenever I declared an attack, the strength of my characters were counted wrong. 
Sometimes every of my characters got -1F (not on first challenge obviously) often on second challenge of the turn but sometimes on third one too. 
Same, but with less frequency (this happen once it seems to me on three games) the +2F of the LOTC were applied on a second challenge. 

Once, we made a wrong input and we played a 4th challenge to compensate a failed one and on this one all my peeps got +2F. 
Whatever the game and the challenge, my characters never add the right force on all challenges for three games. 
As my opponent seems not affected, we supposed this was linked to my agenda LOTC. 

whatever the numbers were right again on resolution calculation. Everytimes. So this was a problem who happening before resolution only. 

for example, this was often worded like that : "Silme attack with 3F (two characters), (....) silme pass, nevevar pass, (...) silme win 9F to 0"
but resolution never failed and was always right on numbers. 

thanks a lot for your answer and future solution !

**Comment by cryogen** [comment]
Thanks for the report.  An update was deployed yesterday which contained the bugs you mention.   It was hotfixed late last evening so the bugs should no longer be present.  Please reopen this issue if that is not the case.

**Comment by silme39** [comment]
Thanks for your answer ! Congrats again for throneteki !

**Comment by ystros** [comment]
Was indeed still an issue when the challenge was declared, fixed in #905. Thanks!
