### ISSUE TITLE
Order of Pillage and indicator of which character is doing the Pillaging

### ISSUE THREAD

**Issue by killerangel1863** [cryogen/throneteki#909]
If possible could you add a prompt when there are multiple Pillage characters in a challenge for the order of their Pillage triggers. This matters when you have characters that trigger off of the cards pillaged and you have some way to stack ("The Bear and the Maiden Fair") or filter (Tywin Lannister (LoCR version)) the opponent's deck. An example of this would be:

You win a challenge with Black Winds Crew (Pillage, but no special abilities), Gregor's Mauraders (Pillage, ability that triggers off pillaging an Event), and Ser Gregor (Pillage, ability that triggers off pillaging a character) with Tywin Lannister (LoCR version) (When a card is discarded from opponent's deck, look at the top 2 and choose which to Pillage) on the board. In this situation it is important to be able to trigger the Black Winds Crew first so that when you look at the top two cards you can decide who to pillage with next in case you see a character you want to kill or an event.

Thanks!

**Comment by IMABUNNEH** [comment]
This hasn't been fixed still and it's still as important as it ever was. It can't be difficult to add a prompt/notification to explain whose pillage is being used while reactions/interrupts to it are happening. Ideally, actually let us choose the order.

**Comment by ystros** [comment]
Please understand that a lot of our priority has been to finish implementing all cards as well as fixing critical bugs. We're closing in on that goal and have begun to spread out to other things now. In allowing Pillage order to be chosen, we've also discussed making keywords like Renown + Insight optional, as well as allowing first player to choose the order of keyword resolution per the rules. These will likely go out at the same time.

As a workaround, please note that Pillage happens in the order you selected attackers currently. So if you were to click Gregor, then click Marauders when selecting attackers, Gregor's pillage will be done first. It isn't ideal, though, hence why this issue exists.
