### ISSUE TITLE
Blood Magic Ritual + Risen from the Sea vs 'no attachment' characters

### ISSUE THREAD

**Issue by nhaok** [cryogen/throneteki#953]
Blood Magic Ritual stays attached to 'no attachments' characters. Correct behaviour is discard.
 
![bloodmagic](https://cloud.githubusercontent.com/assets/25001718/26424295/fc5dadda-40d0-11e7-869b-ae6817ceab6d.png)

**Comment by ystros** [comment]
Thanks! Same problem occurs for Risen from the Sea.
