### ISSUE TITLE
Jon Snow (Core) considered participating after removing attacking characters from challenge

### ISSUE THREAD

**Issue by nhaok** [cryogen/throneteki#954]
When 'remove from challenge' effect ( Areo Hotah, Red Keep Spy, Quaithe, Highgarden etc. ) takes away all attacking characters, Jon Snow str isn't removed.

![jonsnow](https://cloud.githubusercontent.com/assets/25001718/26463855/00376030-4186-11e7-9854-950e814212b9.png)

**Comment by fafranco82** [comment]
Also, If you Nightmare'd Kon Snow he should not be considered participating anymore, but he is.
