### ISSUE TITLE
Brothel Madem should not be automatic

### ISSUE THREAD

**Issue by JalekZem** [cryogen/throneteki#963]
While the dialogue window for Brothel Madame is implemented, it appears to be automatic as long as she is in play.  This should not be the case, as it is not a forced reaction, but rather a reaction that requires the controlling player to activate it.  As such, she can be nightmares or otherwise made unable to use her ability prior to the controlling player being able to perform the action or simply forgotten by the controlling player.

**Comment by DukeTax** [comment]
Hm? Brothel Madame is implemented like any other reaction. Since she reacts to the start of a phase, she can't really be Nightmared, but if she would be Milked, her reaction would not prompt.

**Comment by ystros** [comment]
Brothel Madame is already implemented as a normal reaction, not a forced one. The player is prompted whether to activate her ability or to pass. All reactions / interrupts are implemented this way - the game will automatically prompt you, giving you an opportunity to activate that ability or choose not to by passing.

In the specific case of Brothel Madame, there is no way to play Nightmares to cancel her ability per the rules. Brothel Madame's reaction is to the challenge phase beginning, which happens before the first action window of the challenges phase opens. However, if she's blanked through other means (Fortified Position, Milk of the Poppy, etc) prior to the start of the challenge phase, then her ability will not be prompted or able to activate.

**Comment by JalekZem** [comment]
Well then maybe, the dialogue in the text box should be clearer that player X triggers the BM as the current dialogue makes it appear that it is happening automatically

**Comment by ystros** [comment]
That's fair - there doesn't seem to be a message in chat before the opponent gets asked to pay 1 gold. Do you think a message like "Player 1 uses Brothel Madame. Player 2 must pay 1 gold to initiate military challenges this round" would help?

**Comment by JalekZem** [comment]
that would work, though "Player 1 has elected to use..." would be clearer

**Comment by cryogen** [comment]
We don't typically have preemptive messages like this. The messages happen after the effect has been triggered. As already stated this card is working consistently as all the other cards
