### ISSUE TITLE
Crown of Gold played by different owners end up as duplicates

### ISSUE THREAD

**Issue by zacchiro** [cryogen/throneteki#967]
Scenario:
- mirror match Targ (player A) v. Targ (player B)
- A plays Crown of Gold on a character controlled by B, who doesn't die
- B plays Crown of Gold
- B's Crown becomes a duplicate of A's Crown, rather than as a new copy controller by B

This is likely a more general issue with all unique attachments, by I haven't tried to reproduce it with anything other than Crown of Gold.

**Comment by ystros** [comment]
Fixed by #955.
