### ISSUE TITLE
Winterfell and Euron Crow's Eye

### ISSUE THREAD

**Issue by verbalkint81** [cryogen/throneteki#972]
When my opponent used "we do not sow" to discard my Winterfell and then put it under his control with Euron Crow's Eye, it kept giving my characters buffs, even though it only applies to Stark Characters that the person who controls Winterfell have in play.

**Comment by verbalkint81** [comment]
I should specify, that it the buff I was referring to was the +1 str to all stark characters.

**Comment by ystros** [comment]
Thanks for the report. This bug has already been fixed in #959 but hasn't been applied to the live site yet. So you should see the fix at the next release for the site.

**Comment by verbalkint81** [comment]
Thanks for the reply - just jumping back in to say that I love the site and you're all doing a great job - thanks!
